; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64-unknown-unknown | FileCheck %s

; Test llvm.convert.from.arbitrary intrinsic expansion.

declare float @llvm.convert.from.arbitrary.fp.f32.i8(i8, metadata)
declare float @llvm.convert.from.arbitrary.fp.f32.i6(i6, metadata)
declare float @llvm.convert.from.arbitrary.fp.f32.i4(i4, metadata)
declare <4 x float> @llvm.convert.from.arbitrary.fp.v4f32.v4i4(<4 x i4>, metadata)

declare half @llvm.convert.from.arbitrary.fp.f16.i8(i8, metadata)
declare double @llvm.convert.from.arbitrary.fp.f64.i8(i8, metadata)

; Float8E5M2
; Layout: sign(1) exp(5) mant(2), bias=15
; Supports: Inf, NaN, signed zero, denormals

; Float8E5M2 normal: 0_01111_00 = 1.0
define float @from_f8e5m2_normal() {
; CHECK-LABEL: from_f8e5m2_normal(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1065353216;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 60, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 zero: 0_00000_00 = +0.0
define float @from_f8e5m2_zero() {
; CHECK-LABEL: from_f8e5m2_zero(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 0;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 negative zero: 1_00000_00 = -0.0
define float @from_f8e5m2_neg_zero() {
; CHECK-LABEL: from_f8e5m2_neg_zero(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], -2147483648;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -128, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 denorm: 0_00000_01 = 2^(-16)
define float @from_f8e5m2_denorm() {
; CHECK-LABEL: from_f8e5m2_denorm(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 931135488;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 1, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 +Inf: 0_11111_00
define float @from_f8e5m2_inf() {
; CHECK-LABEL: from_f8e5m2_inf(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 2139095040;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 124, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 NaN: 0_11111_01
define float @from_f8e5m2_nan() {
; CHECK-LABEL: from_f8e5m2_nan(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 2143289344;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 125, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 max: 0_11110_11 = 57344
define float @from_f8e5m2_max() {
; CHECK-LABEL: from_f8e5m2_max(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1197473792;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 123, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 negative: 1_01111_00 = -1.0
define float @from_f8e5m2_neg() {
; CHECK-LABEL: from_f8e5m2_neg(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], -1082130432;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -68, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 runtime arg test
define float @from_f8e5m2_dynamic(i8 %x) {
; CHECK-LABEL: from_f8e5m2_dynamic(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<12>;
; CHECK-NEXT:    .reg .b32 %r<34>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %r1, [from_f8e5m2_dynamic_param_0];
; CHECK-NEXT:    shl.b32 %r2, %r1, 24;
; CHECK-NEXT:    and.b32 %r3, %r2, -2147483648;
; CHECK-NEXT:    and.b32 %r4, %r1, 3;
; CHECK-NEXT:    clz.b32 %r5, %r4;
; CHECK-NEXT:    sub.s32 %r6, 142, %r5;
; CHECK-NEXT:    shl.b32 %r7, %r6, 23;
; CHECK-NEXT:    or.b32 %r8, %r3, %r7;
; CHECK-NEXT:    sub.s32 %r9, 31, %r5;
; CHECK-NEXT:    mov.b32 %r10, 1;
; CHECK-NEXT:    shl.b32 %r11, %r10, %r9;
; CHECK-NEXT:    xor.b32 %r12, %r4, %r11;
; CHECK-NEXT:    add.s32 %r13, %r5, -8;
; CHECK-NEXT:    shl.b32 %r14, %r12, %r13;
; CHECK-NEXT:    or.b32 %r15, %r8, %r14;
; CHECK-NEXT:    bfe.u32 %r16, %r1, 2, 5;
; CHECK-NEXT:    add.s32 %r17, %r16, 112;
; CHECK-NEXT:    shl.b32 %r18, %r17, 23;
; CHECK-NEXT:    or.b32 %r19, %r3, %r18;
; CHECK-NEXT:    shl.b32 %r20, %r4, 21;
; CHECK-NEXT:    or.b32 %r21, %r19, %r20;
; CHECK-NEXT:    setp.ne.b32 %p1, %r4, 0;
; CHECK-NEXT:    selp.b32 %r22, %r15, %r21, %p1;
; CHECK-NEXT:    setp.eq.b32 %p2, %r16, 0;
; CHECK-NEXT:    selp.b32 %r23, %r22, %r21, %p2;
; CHECK-NEXT:    setp.gt.u32 %p3, %r17, 254;
; CHECK-NEXT:    or.b32 %r24, %r3, 2139095040;
; CHECK-NEXT:    selp.b32 %r25, %r24, %r23, %p3;
; CHECK-NEXT:    setp.eq.b32 %p4, %r16, 31;
; CHECK-NEXT:    and.pred %p5, %p4, %p1;
; CHECK-NEXT:    not.pred %p6, %p5;
; CHECK-NEXT:    setp.ne.b32 %p7, %r16, 0;
; CHECK-NEXT:    and.pred %p8, %p7, %p6;
; CHECK-NEXT:    selp.b32 %r26, %r25, %r23, %p8;
; CHECK-NEXT:    setp.lt.s32 %p9, %r17, 1;
; CHECK-NEXT:    selp.b32 %r27, %r3, %r26, %p9;
; CHECK-NEXT:    selp.b32 %r28, %r27, %r26, %p8;
; CHECK-NEXT:    or.b32 %r29, %r16, %r4;
; CHECK-NEXT:    setp.eq.b32 %p10, %r29, 0;
; CHECK-NEXT:    selp.b32 %r30, %r3, %r28, %p10;
; CHECK-NEXT:    setp.eq.b32 %p11, %r4, 0;
; CHECK-NEXT:    selp.b32 %r31, %r24, %r30, %p11;
; CHECK-NEXT:    selp.b32 %r32, %r31, %r30, %p4;
; CHECK-NEXT:    selp.b32 %r33, 2143289344, %r32, %p5;
; CHECK-NEXT:    st.param.b32 [func_retval0], %r33;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 %x, metadata !"Float8E5M2")
  ret float %r
}

; Float8E4M3FN (NanOnly, NanEncoding=AllOnes)
; Layout: sign(1) exp(4) mant(3), maxExp=8, minExp=-6, bias=7
; Only 0_1111_111 and 1_1111_111 are NaN; all other exp=15 values are finite.

; Float8E4M3FN normal: 0_0111_000 = 1.0
define float @from_f8e4m3fn_normal() {
; CHECK-LABEL: from_f8e4m3fn_normal(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1065353216;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 56, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN NaN: 0_1111_111
define float @from_f8e4m3fn_nan() {
; CHECK-LABEL: from_f8e4m3fn_nan(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 2143289344;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 127, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN not-NaN: 0_1111_110 = 448
; Despite exp=all-ones, this is a valid finite number (max value)
define float @from_f8e4m3fn_max() {
; CHECK-LABEL: from_f8e4m3fn_max(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1138753536;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 126, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN not-NaN: 0_1111_101 = 416
; exp=all-ones but mant!=all-ones so this is finite
define float @from_f8e4m3fn_not_nan() {
; CHECK-LABEL: from_f8e4m3fn_not_nan(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1137704960;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 125, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN zero: 0_0000_000 = +0.0
define float @from_f8e4m3fn_zero() {
; CHECK-LABEL: from_f8e4m3fn_zero(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 0;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN denorm: 0_0000_001 = 2^(-9)
define float @from_f8e4m3fn_denorm() {
; CHECK-LABEL: from_f8e4m3fn_denorm(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 989855744;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 1, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN runtime arg test
define float @from_f8e4m3fn_dynamic(i8 %x) {
; CHECK-LABEL: from_f8e4m3fn_dynamic(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<12>;
; CHECK-NEXT:    .reg .b32 %r<32>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %r1, [from_f8e4m3fn_dynamic_param_0];
; CHECK-NEXT:    shl.b32 %r2, %r1, 24;
; CHECK-NEXT:    and.b32 %r3, %r2, -2147483648;
; CHECK-NEXT:    and.b32 %r4, %r1, 7;
; CHECK-NEXT:    clz.b32 %r5, %r4;
; CHECK-NEXT:    sub.s32 %r6, 149, %r5;
; CHECK-NEXT:    shl.b32 %r7, %r6, 23;
; CHECK-NEXT:    or.b32 %r8, %r3, %r7;
; CHECK-NEXT:    sub.s32 %r9, 31, %r5;
; CHECK-NEXT:    mov.b32 %r10, 1;
; CHECK-NEXT:    shl.b32 %r11, %r10, %r9;
; CHECK-NEXT:    xor.b32 %r12, %r4, %r11;
; CHECK-NEXT:    add.s32 %r13, %r5, -8;
; CHECK-NEXT:    shl.b32 %r14, %r12, %r13;
; CHECK-NEXT:    or.b32 %r15, %r8, %r14;
; CHECK-NEXT:    bfe.u32 %r16, %r1, 3, 4;
; CHECK-NEXT:    add.s32 %r17, %r16, 120;
; CHECK-NEXT:    shl.b32 %r18, %r17, 23;
; CHECK-NEXT:    or.b32 %r19, %r3, %r18;
; CHECK-NEXT:    shl.b32 %r20, %r4, 20;
; CHECK-NEXT:    or.b32 %r21, %r19, %r20;
; CHECK-NEXT:    setp.ne.b32 %p1, %r4, 0;
; CHECK-NEXT:    selp.b32 %r22, %r15, %r21, %p1;
; CHECK-NEXT:    setp.eq.b32 %p2, %r16, 0;
; CHECK-NEXT:    selp.b32 %r23, %r22, %r21, %p2;
; CHECK-NEXT:    setp.gt.u32 %p3, %r17, 254;
; CHECK-NEXT:    or.b32 %r24, %r3, 2139095040;
; CHECK-NEXT:    selp.b32 %r25, %r24, %r23, %p3;
; CHECK-NEXT:    setp.eq.b32 %p4, %r4, 7;
; CHECK-NEXT:    setp.eq.b32 %p5, %r16, 15;
; CHECK-NEXT:    and.pred %p6, %p5, %p4;
; CHECK-NEXT:    not.pred %p7, %p6;
; CHECK-NEXT:    setp.ne.b32 %p8, %r16, 0;
; CHECK-NEXT:    and.pred %p9, %p8, %p7;
; CHECK-NEXT:    selp.b32 %r26, %r25, %r23, %p9;
; CHECK-NEXT:    setp.lt.s32 %p10, %r17, 1;
; CHECK-NEXT:    selp.b32 %r27, %r3, %r26, %p10;
; CHECK-NEXT:    selp.b32 %r28, %r27, %r26, %p9;
; CHECK-NEXT:    or.b32 %r29, %r16, %r4;
; CHECK-NEXT:    setp.eq.b32 %p11, %r29, 0;
; CHECK-NEXT:    selp.b32 %r30, %r3, %r28, %p11;
; CHECK-NEXT:    selp.b32 %r31, 2143289344, %r30, %p6;
; CHECK-NEXT:    st.param.b32 [func_retval0], %r31;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 %x, metadata !"Float8E4M3FN")
  ret float %r
}

; Float6E3M2FN (FiniteOnly)
; Layout: sign(1) exp(3) mant(2), bias=3, maxExp=4
; No Inf, no NaN. All bit patterns are finite.

; Float6E3M2FN normal: 0_011_00 = 1.0
define float @from_f6e3m2fn_normal() {
; CHECK-LABEL: from_f6e3m2fn_normal(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1065353216;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 12, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN max: 0_111_11 = 28.0
define float @from_f6e3m2fn_max() {
; CHECK-LABEL: from_f6e3m2fn_max(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1105199104;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 31, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN denorm: 0_000_01 = 0.0625
define float @from_f6e3m2fn_denorm() {
; CHECK-LABEL: from_f6e3m2fn_denorm(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1031798784;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 1, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN zero: 0_000_00 = +0.0
define float @from_f6e3m2fn_zero() {
; CHECK-LABEL: from_f6e3m2fn_zero(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 0;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 0, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN negative: 1_011_00 = -1.0
define float @from_f6e3m2fn_neg() {
; CHECK-LABEL: from_f6e3m2fn_neg(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], -1082130432;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 -20, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN runtime arg test
define float @from_f6e3m2fn_dynamic(i6 %x) {
; CHECK-LABEL: from_f6e3m2fn_dynamic(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<6>;
; CHECK-NEXT:    .reg .b16 %rs<5>;
; CHECK-NEXT:    .reg .b32 %r<31>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [from_f6e3m2fn_dynamic_param_0+1];
; CHECK-NEXT:    shl.b16 %rs2, %rs1, 8;
; CHECK-NEXT:    ld.param.b8 %rs3, [from_f6e3m2fn_dynamic_param_0];
; CHECK-NEXT:    or.b16 %rs4, %rs2, %rs3;
; CHECK-NEXT:    cvt.u32.u16 %r1, %rs4;
; CHECK-NEXT:    shl.b32 %r2, %r1, 26;
; CHECK-NEXT:    and.b32 %r3, %r2, -2147483648;
; CHECK-NEXT:    and.b32 %r4, %r1, 3;
; CHECK-NEXT:    clz.b32 %r5, %r4;
; CHECK-NEXT:    sub.s32 %r6, 154, %r5;
; CHECK-NEXT:    shl.b32 %r7, %r6, 23;
; CHECK-NEXT:    or.b32 %r8, %r3, %r7;
; CHECK-NEXT:    sub.s32 %r9, 31, %r5;
; CHECK-NEXT:    mov.b32 %r10, 1;
; CHECK-NEXT:    shl.b32 %r11, %r10, %r9;
; CHECK-NEXT:    xor.b32 %r12, %r4, %r11;
; CHECK-NEXT:    add.s32 %r13, %r5, -8;
; CHECK-NEXT:    shl.b32 %r14, %r12, %r13;
; CHECK-NEXT:    or.b32 %r15, %r8, %r14;
; CHECK-NEXT:    bfe.u32 %r16, %r1, 2, 3;
; CHECK-NEXT:    add.s32 %r17, %r16, 124;
; CHECK-NEXT:    shl.b32 %r18, %r17, 23;
; CHECK-NEXT:    or.b32 %r19, %r3, %r18;
; CHECK-NEXT:    shl.b32 %r20, %r4, 21;
; CHECK-NEXT:    or.b32 %r21, %r19, %r20;
; CHECK-NEXT:    setp.ne.b32 %p1, %r4, 0;
; CHECK-NEXT:    selp.b32 %r22, %r15, %r21, %p1;
; CHECK-NEXT:    setp.eq.b32 %p2, %r16, 0;
; CHECK-NEXT:    selp.b32 %r23, %r22, %r21, %p2;
; CHECK-NEXT:    setp.gt.u32 %p3, %r17, 254;
; CHECK-NEXT:    or.b32 %r24, %r3, 2139095040;
; CHECK-NEXT:    selp.b32 %r25, %r24, %r23, %p3;
; CHECK-NEXT:    selp.b32 %r26, %r23, %r25, %p2;
; CHECK-NEXT:    setp.lt.s32 %p4, %r17, 1;
; CHECK-NEXT:    selp.b32 %r27, %r3, %r26, %p4;
; CHECK-NEXT:    selp.b32 %r28, %r26, %r27, %p2;
; CHECK-NEXT:    or.b32 %r29, %r16, %r4;
; CHECK-NEXT:    setp.eq.b32 %p5, %r29, 0;
; CHECK-NEXT:    selp.b32 %r30, %r3, %r28, %p5;
; CHECK-NEXT:    st.param.b32 [func_retval0], %r30;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 %x, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E2M3FN (FiniteOnly)
; Layout: sign(1) exp(2) mant(3), bias=1, maxExp=2
; No Inf, no NaN. All bit patterns are finite.

; Float6E2M3FN normal: 0_01_000 = 1.0
define float @from_f6e2m3fn_normal() {
; CHECK-LABEL: from_f6e2m3fn_normal(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1065353216;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 8, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN max: 0_11_111 = 7.5
define float @from_f6e2m3fn_max() {
; CHECK-LABEL: from_f6e2m3fn_max(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1089470464;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 31, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN denorm: 0_00_001 = 0.125
define float @from_f6e2m3fn_denorm() {
; CHECK-LABEL: from_f6e2m3fn_denorm(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1040187392;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 1, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN zero: 0_00_000 = +0.0
define float @from_f6e2m3fn_zero() {
; CHECK-LABEL: from_f6e2m3fn_zero(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 0;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 0, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN runtime arg test
define float @from_f6e2m3fn_dynamic(i6 %x) {
; CHECK-LABEL: from_f6e2m3fn_dynamic(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<6>;
; CHECK-NEXT:    .reg .b16 %rs<5>;
; CHECK-NEXT:    .reg .b32 %r<31>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [from_f6e2m3fn_dynamic_param_0+1];
; CHECK-NEXT:    shl.b16 %rs2, %rs1, 8;
; CHECK-NEXT:    ld.param.b8 %rs3, [from_f6e2m3fn_dynamic_param_0];
; CHECK-NEXT:    or.b16 %rs4, %rs2, %rs3;
; CHECK-NEXT:    cvt.u32.u16 %r1, %rs4;
; CHECK-NEXT:    shl.b32 %r2, %r1, 26;
; CHECK-NEXT:    and.b32 %r3, %r2, -2147483648;
; CHECK-NEXT:    and.b32 %r4, %r1, 7;
; CHECK-NEXT:    clz.b32 %r5, %r4;
; CHECK-NEXT:    sub.s32 %r6, 155, %r5;
; CHECK-NEXT:    shl.b32 %r7, %r6, 23;
; CHECK-NEXT:    or.b32 %r8, %r3, %r7;
; CHECK-NEXT:    sub.s32 %r9, 31, %r5;
; CHECK-NEXT:    mov.b32 %r10, 1;
; CHECK-NEXT:    shl.b32 %r11, %r10, %r9;
; CHECK-NEXT:    xor.b32 %r12, %r4, %r11;
; CHECK-NEXT:    add.s32 %r13, %r5, -8;
; CHECK-NEXT:    shl.b32 %r14, %r12, %r13;
; CHECK-NEXT:    or.b32 %r15, %r8, %r14;
; CHECK-NEXT:    bfe.u32 %r16, %r1, 3, 2;
; CHECK-NEXT:    add.s32 %r17, %r16, 126;
; CHECK-NEXT:    shl.b32 %r18, %r17, 23;
; CHECK-NEXT:    or.b32 %r19, %r3, %r18;
; CHECK-NEXT:    shl.b32 %r20, %r4, 20;
; CHECK-NEXT:    or.b32 %r21, %r19, %r20;
; CHECK-NEXT:    setp.ne.b32 %p1, %r4, 0;
; CHECK-NEXT:    selp.b32 %r22, %r15, %r21, %p1;
; CHECK-NEXT:    setp.eq.b32 %p2, %r16, 0;
; CHECK-NEXT:    selp.b32 %r23, %r22, %r21, %p2;
; CHECK-NEXT:    setp.gt.u32 %p3, %r17, 254;
; CHECK-NEXT:    or.b32 %r24, %r3, 2139095040;
; CHECK-NEXT:    selp.b32 %r25, %r24, %r23, %p3;
; CHECK-NEXT:    selp.b32 %r26, %r23, %r25, %p2;
; CHECK-NEXT:    setp.lt.s32 %p4, %r17, 1;
; CHECK-NEXT:    selp.b32 %r27, %r3, %r26, %p4;
; CHECK-NEXT:    selp.b32 %r28, %r26, %r27, %p2;
; CHECK-NEXT:    or.b32 %r29, %r16, %r4;
; CHECK-NEXT:    setp.eq.b32 %p5, %r29, 0;
; CHECK-NEXT:    selp.b32 %r30, %r3, %r28, %p5;
; CHECK-NEXT:    st.param.b32 [func_retval0], %r30;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 %x, metadata !"Float6E2M3FN")
  ret float %r
}

; Float4E2M1FN (FiniteOnly)
; Layout: sign(1) exp(2) mant(1), bias=1, maxExp=2
; No Inf, no NaN.

; Float4E2M1FN normal: 0_01_0 = 1.0
define float @from_f4e2m1fn_normal() {
; CHECK-LABEL: from_f4e2m1fn_normal(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1065353216;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 2, metadata !"Float4E2M1FN")
  ret float %r
}

; Float4E2M1FN denorm: 0_00_1 = 0.5
define float @from_f4e2m1fn_denorm() {
; CHECK-LABEL: from_f4e2m1fn_denorm(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1056964608;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 1, metadata !"Float4E2M1FN")
  ret float %r
}

; Float4E2M1FN max: 0_11_1 = 6.0
define float @from_f4e2m1fn_max() {
; CHECK-LABEL: from_f4e2m1fn_max(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b32 [func_retval0], 1086324736;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 7, metadata !"Float4E2M1FN")
  ret float %r
}

; Float4E2M1FN runtime arg test
define float @from_f4e2m1fn_dynamic(i4 %x) {
; CHECK-LABEL: from_f4e2m1fn_dynamic(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<6>;
; CHECK-NEXT:    .reg .b16 %rs<6>;
; CHECK-NEXT:    .reg .b32 %r<31>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [from_f4e2m1fn_dynamic_param_0+1];
; CHECK-NEXT:    shl.b16 %rs2, %rs1, 8;
; CHECK-NEXT:    ld.param.b8 %rs3, [from_f4e2m1fn_dynamic_param_0];
; CHECK-NEXT:    or.b16 %rs4, %rs2, %rs3;
; CHECK-NEXT:    cvt.u32.u16 %r1, %rs4;
; CHECK-NEXT:    shl.b32 %r2, %r1, 28;
; CHECK-NEXT:    and.b32 %r3, %r2, -2147483648;
; CHECK-NEXT:    and.b32 %r4, %r1, 1;
; CHECK-NEXT:    clz.b32 %r5, %r4;
; CHECK-NEXT:    sub.s32 %r6, 157, %r5;
; CHECK-NEXT:    shl.b32 %r7, %r6, 23;
; CHECK-NEXT:    or.b32 %r8, %r3, %r7;
; CHECK-NEXT:    sub.s32 %r9, 31, %r5;
; CHECK-NEXT:    mov.b32 %r10, 1;
; CHECK-NEXT:    shl.b32 %r11, %r10, %r9;
; CHECK-NEXT:    xor.b32 %r12, %r4, %r11;
; CHECK-NEXT:    add.s32 %r13, %r5, -8;
; CHECK-NEXT:    shl.b32 %r14, %r12, %r13;
; CHECK-NEXT:    or.b32 %r15, %r8, %r14;
; CHECK-NEXT:    bfe.u32 %r16, %r1, 1, 2;
; CHECK-NEXT:    add.s32 %r17, %r16, 126;
; CHECK-NEXT:    shl.b32 %r18, %r17, 23;
; CHECK-NEXT:    or.b32 %r19, %r3, %r18;
; CHECK-NEXT:    shl.b32 %r20, %r4, 22;
; CHECK-NEXT:    or.b32 %r21, %r19, %r20;
; CHECK-NEXT:    and.b16 %rs5, %rs3, 1;
; CHECK-NEXT:    setp.ne.b16 %p1, %rs5, 0;
; CHECK-NEXT:    selp.b32 %r22, %r15, %r21, %p1;
; CHECK-NEXT:    setp.eq.b32 %p2, %r16, 0;
; CHECK-NEXT:    selp.b32 %r23, %r22, %r21, %p2;
; CHECK-NEXT:    setp.gt.u32 %p3, %r17, 254;
; CHECK-NEXT:    or.b32 %r24, %r3, 2139095040;
; CHECK-NEXT:    selp.b32 %r25, %r24, %r23, %p3;
; CHECK-NEXT:    selp.b32 %r26, %r23, %r25, %p2;
; CHECK-NEXT:    setp.lt.s32 %p4, %r17, 1;
; CHECK-NEXT:    selp.b32 %r27, %r3, %r26, %p4;
; CHECK-NEXT:    selp.b32 %r28, %r26, %r27, %p2;
; CHECK-NEXT:    or.b32 %r29, %r16, %r4;
; CHECK-NEXT:    setp.eq.b32 %p5, %r29, 0;
; CHECK-NEXT:    selp.b32 %r30, %r3, %r28, %p5;
; CHECK-NEXT:    st.param.b32 [func_retval0], %r30;
; CHECK-NEXT:    ret;
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 %x, metadata !"Float4E2M1FN")
  ret float %r
}

; Float8E5M2 to f16: 1.0
define half @from_f8e5m2_to_f16() {
; CHECK-LABEL: from_f8e5m2_to_f16(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b16 [func_retval0], 0x3C00;
; CHECK-NEXT:    ret;
  %r = call half @llvm.convert.from.arbitrary.fp.f16.i8(i8 60, metadata !"Float8E5M2")
  ret half %r
}

; Float8E5M2 to f64: 1.0
define double @from_f8e5m2_to_f64() {
; CHECK-LABEL: from_f8e5m2_to_f64(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    st.param.b64 [func_retval0], 4607182418800017408;
; CHECK-NEXT:    ret;
  %r = call double @llvm.convert.from.arbitrary.fp.f64.i8(i8 60, metadata !"Float8E5M2")
  ret double %r
}

; Vector test: Float4E2M1FN <4 x i4> -> <4 x float>
define <4 x float> @fp4_to_f32_vec(<4 x i4> %x) {
; CHECK-LABEL: fp4_to_f32_vec(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<21>;
; CHECK-NEXT:    .reg .b32 %r<121>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %r1, [fp4_to_f32_vec_param_0+2];
; CHECK-NEXT:    shl.b32 %r2, %r1, 16;
; CHECK-NEXT:    ld.param.b16 %r3, [fp4_to_f32_vec_param_0];
; CHECK-NEXT:    prmt.b32 %r4, %r3, 0, 0x7771U;
; CHECK-NEXT:    shl.b32 %r5, %r4, 28;
; CHECK-NEXT:    and.b32 %r6, %r5, -2147483648;
; CHECK-NEXT:    and.b32 %r7, %r4, 1;
; CHECK-NEXT:    clz.b32 %r8, %r7;
; CHECK-NEXT:    sub.s32 %r9, 157, %r8;
; CHECK-NEXT:    shl.b32 %r10, %r9, 23;
; CHECK-NEXT:    or.b32 %r11, %r6, %r10;
; CHECK-NEXT:    sub.s32 %r12, 31, %r8;
; CHECK-NEXT:    mov.b32 %r13, 1;
; CHECK-NEXT:    shl.b32 %r14, %r13, %r12;
; CHECK-NEXT:    xor.b32 %r15, %r7, %r14;
; CHECK-NEXT:    add.s32 %r16, %r8, -8;
; CHECK-NEXT:    shl.b32 %r17, %r15, %r16;
; CHECK-NEXT:    or.b32 %r18, %r11, %r17;
; CHECK-NEXT:    bfe.u32 %r19, %r4, 1, 2;
; CHECK-NEXT:    add.s32 %r20, %r19, 126;
; CHECK-NEXT:    shl.b32 %r21, %r20, 23;
; CHECK-NEXT:    or.b32 %r22, %r6, %r21;
; CHECK-NEXT:    shl.b32 %r23, %r7, 22;
; CHECK-NEXT:    or.b32 %r24, %r22, %r23;
; CHECK-NEXT:    setp.ne.b32 %p1, %r7, 0;
; CHECK-NEXT:    selp.b32 %r25, %r18, %r24, %p1;
; CHECK-NEXT:    setp.eq.b32 %p2, %r19, 0;
; CHECK-NEXT:    selp.b32 %r26, %r25, %r24, %p2;
; CHECK-NEXT:    setp.gt.u32 %p3, %r20, 254;
; CHECK-NEXT:    or.b32 %r27, %r6, 2139095040;
; CHECK-NEXT:    selp.b32 %r28, %r27, %r26, %p3;
; CHECK-NEXT:    selp.b32 %r29, %r26, %r28, %p2;
; CHECK-NEXT:    setp.lt.s32 %p4, %r20, 1;
; CHECK-NEXT:    selp.b32 %r30, %r6, %r29, %p4;
; CHECK-NEXT:    selp.b32 %r31, %r29, %r30, %p2;
; CHECK-NEXT:    or.b32 %r32, %r19, %r7;
; CHECK-NEXT:    setp.eq.b32 %p5, %r32, 0;
; CHECK-NEXT:    selp.b32 %r33, %r6, %r31, %p5;
; CHECK-NEXT:    prmt.b32 %r34, %r3, 0, 0x7770U;
; CHECK-NEXT:    shl.b32 %r35, %r34, 28;
; CHECK-NEXT:    and.b32 %r36, %r35, -2147483648;
; CHECK-NEXT:    and.b32 %r37, %r34, 1;
; CHECK-NEXT:    clz.b32 %r38, %r37;
; CHECK-NEXT:    sub.s32 %r39, 157, %r38;
; CHECK-NEXT:    shl.b32 %r40, %r39, 23;
; CHECK-NEXT:    or.b32 %r41, %r36, %r40;
; CHECK-NEXT:    sub.s32 %r42, 31, %r38;
; CHECK-NEXT:    shl.b32 %r43, %r13, %r42;
; CHECK-NEXT:    xor.b32 %r44, %r37, %r43;
; CHECK-NEXT:    add.s32 %r45, %r38, -8;
; CHECK-NEXT:    shl.b32 %r46, %r44, %r45;
; CHECK-NEXT:    or.b32 %r47, %r41, %r46;
; CHECK-NEXT:    bfe.u32 %r48, %r34, 1, 2;
; CHECK-NEXT:    add.s32 %r49, %r48, 126;
; CHECK-NEXT:    shl.b32 %r50, %r49, 23;
; CHECK-NEXT:    or.b32 %r51, %r36, %r50;
; CHECK-NEXT:    shl.b32 %r52, %r37, 22;
; CHECK-NEXT:    or.b32 %r53, %r51, %r52;
; CHECK-NEXT:    setp.ne.b32 %p6, %r37, 0;
; CHECK-NEXT:    selp.b32 %r54, %r47, %r53, %p6;
; CHECK-NEXT:    setp.eq.b32 %p7, %r48, 0;
; CHECK-NEXT:    selp.b32 %r55, %r54, %r53, %p7;
; CHECK-NEXT:    setp.gt.u32 %p8, %r49, 254;
; CHECK-NEXT:    or.b32 %r56, %r36, 2139095040;
; CHECK-NEXT:    selp.b32 %r57, %r56, %r55, %p8;
; CHECK-NEXT:    selp.b32 %r58, %r55, %r57, %p7;
; CHECK-NEXT:    setp.lt.s32 %p9, %r49, 1;
; CHECK-NEXT:    selp.b32 %r59, %r36, %r58, %p9;
; CHECK-NEXT:    selp.b32 %r60, %r58, %r59, %p7;
; CHECK-NEXT:    or.b32 %r61, %r48, %r37;
; CHECK-NEXT:    setp.eq.b32 %p10, %r61, 0;
; CHECK-NEXT:    selp.b32 %r62, %r36, %r60, %p10;
; CHECK-NEXT:    prmt.b32 %r63, %r2, 0, 0x7773U;
; CHECK-NEXT:    shl.b32 %r64, %r63, 28;
; CHECK-NEXT:    and.b32 %r65, %r64, -2147483648;
; CHECK-NEXT:    and.b32 %r66, %r63, 1;
; CHECK-NEXT:    clz.b32 %r67, %r66;
; CHECK-NEXT:    sub.s32 %r68, 157, %r67;
; CHECK-NEXT:    shl.b32 %r69, %r68, 23;
; CHECK-NEXT:    or.b32 %r70, %r65, %r69;
; CHECK-NEXT:    sub.s32 %r71, 31, %r67;
; CHECK-NEXT:    shl.b32 %r72, %r13, %r71;
; CHECK-NEXT:    xor.b32 %r73, %r66, %r72;
; CHECK-NEXT:    add.s32 %r74, %r67, -8;
; CHECK-NEXT:    shl.b32 %r75, %r73, %r74;
; CHECK-NEXT:    or.b32 %r76, %r70, %r75;
; CHECK-NEXT:    bfe.u32 %r77, %r63, 1, 2;
; CHECK-NEXT:    add.s32 %r78, %r77, 126;
; CHECK-NEXT:    shl.b32 %r79, %r78, 23;
; CHECK-NEXT:    or.b32 %r80, %r65, %r79;
; CHECK-NEXT:    shl.b32 %r81, %r66, 22;
; CHECK-NEXT:    or.b32 %r82, %r80, %r81;
; CHECK-NEXT:    setp.ne.b32 %p11, %r66, 0;
; CHECK-NEXT:    selp.b32 %r83, %r76, %r82, %p11;
; CHECK-NEXT:    setp.eq.b32 %p12, %r77, 0;
; CHECK-NEXT:    selp.b32 %r84, %r83, %r82, %p12;
; CHECK-NEXT:    setp.gt.u32 %p13, %r78, 254;
; CHECK-NEXT:    or.b32 %r85, %r65, 2139095040;
; CHECK-NEXT:    selp.b32 %r86, %r85, %r84, %p13;
; CHECK-NEXT:    selp.b32 %r87, %r84, %r86, %p12;
; CHECK-NEXT:    setp.lt.s32 %p14, %r78, 1;
; CHECK-NEXT:    selp.b32 %r88, %r65, %r87, %p14;
; CHECK-NEXT:    selp.b32 %r89, %r87, %r88, %p12;
; CHECK-NEXT:    or.b32 %r90, %r77, %r66;
; CHECK-NEXT:    setp.eq.b32 %p15, %r90, 0;
; CHECK-NEXT:    selp.b32 %r91, %r65, %r89, %p15;
; CHECK-NEXT:    prmt.b32 %r92, %r2, 0, 0x7772U;
; CHECK-NEXT:    shl.b32 %r93, %r92, 28;
; CHECK-NEXT:    and.b32 %r94, %r93, -2147483648;
; CHECK-NEXT:    and.b32 %r95, %r92, 1;
; CHECK-NEXT:    clz.b32 %r96, %r95;
; CHECK-NEXT:    sub.s32 %r97, 157, %r96;
; CHECK-NEXT:    shl.b32 %r98, %r97, 23;
; CHECK-NEXT:    or.b32 %r99, %r94, %r98;
; CHECK-NEXT:    sub.s32 %r100, 31, %r96;
; CHECK-NEXT:    shl.b32 %r101, %r13, %r100;
; CHECK-NEXT:    xor.b32 %r102, %r95, %r101;
; CHECK-NEXT:    add.s32 %r103, %r96, -8;
; CHECK-NEXT:    shl.b32 %r104, %r102, %r103;
; CHECK-NEXT:    or.b32 %r105, %r99, %r104;
; CHECK-NEXT:    bfe.u32 %r106, %r92, 1, 2;
; CHECK-NEXT:    add.s32 %r107, %r106, 126;
; CHECK-NEXT:    shl.b32 %r108, %r107, 23;
; CHECK-NEXT:    or.b32 %r109, %r94, %r108;
; CHECK-NEXT:    shl.b32 %r110, %r95, 22;
; CHECK-NEXT:    or.b32 %r111, %r109, %r110;
; CHECK-NEXT:    setp.ne.b32 %p16, %r95, 0;
; CHECK-NEXT:    selp.b32 %r112, %r105, %r111, %p16;
; CHECK-NEXT:    setp.eq.b32 %p17, %r106, 0;
; CHECK-NEXT:    selp.b32 %r113, %r112, %r111, %p17;
; CHECK-NEXT:    setp.gt.u32 %p18, %r107, 254;
; CHECK-NEXT:    or.b32 %r114, %r94, 2139095040;
; CHECK-NEXT:    selp.b32 %r115, %r114, %r113, %p18;
; CHECK-NEXT:    selp.b32 %r116, %r113, %r115, %p17;
; CHECK-NEXT:    setp.lt.s32 %p19, %r107, 1;
; CHECK-NEXT:    selp.b32 %r117, %r94, %r116, %p19;
; CHECK-NEXT:    selp.b32 %r118, %r116, %r117, %p17;
; CHECK-NEXT:    or.b32 %r119, %r106, %r95;
; CHECK-NEXT:    setp.eq.b32 %p20, %r119, 0;
; CHECK-NEXT:    selp.b32 %r120, %r94, %r118, %p20;
; CHECK-NEXT:    st.param.v4.b32 [func_retval0], {%r62, %r33, %r120, %r91};
; CHECK-NEXT:    ret;
  %r = call <4 x float> @llvm.convert.from.arbitrary.fp.v4f32.v4i4(<4 x i4> %x, metadata !"Float4E2M1FN")
  ret <4 x float> %r
}
