; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -passes=amdgpu-optimize-barriers %s | FileCheck %s

@lds = internal addrspace(3) global [64 x i32] poison

declare void @llvm.amdgcn.s.barrier()
declare void @llvm.amdgcn.ds.gws.barrier(i32, i32)
declare void @ext()

; One inlined syncthreads triplet is redundant. The first barrier is covered
; forward by the second and the first release fence by the second release.
; The acquire fence between the barriers survives because a cover beyond a
; barrier is not honored.
define amdgpu_kernel void @double_syncthreads(ptr addrspace(1) %out) {
; CHECK-LABEL: @double_syncthreads(
; CHECK-NEXT:    store i32 1, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    fence syncscope("workgroup") acquire
; CHECK-NEXT:    fence syncscope("workgroup") release
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    fence syncscope("workgroup") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(3) @lds
  fence syncscope("workgroup") release
  call void @llvm.amdgcn.s.barrier()
  fence syncscope("workgroup") acquire
  fence syncscope("workgroup") release
  call void @llvm.amdgcn.s.barrier()
  fence syncscope("workgroup") acquire
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(1) %out
  ret void
}

; An LDS store between the barriers keeps both.
define amdgpu_kernel void @barrier_needed(ptr addrspace(1) %out) {
; CHECK-LABEL: @barrier_needed(
; CHECK-NEXT:    store i32 1, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    fence syncscope("workgroup") release
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    fence syncscope("workgroup") acquire
; CHECK-NEXT:    store i32 2, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 1), align 4
; CHECK-NEXT:    fence syncscope("workgroup") release
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    fence syncscope("workgroup") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(3) @lds
  fence syncscope("workgroup") release
  call void @llvm.amdgcn.s.barrier()
  fence syncscope("workgroup") acquire
  store i32 2, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 1)
  fence syncscope("workgroup") release
  call void @llvm.amdgcn.s.barrier()
  fence syncscope("workgroup") acquire
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(1) %out
  ret void
}

; Agent fences whose reachable shared accesses are all LDS narrow to
; workgroup scope.
define amdgpu_kernel void @narrow_lds_only() {
; CHECK-LABEL: @narrow_lds_only(
; CHECK-NEXT:    store i32 1, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    fence syncscope("workgroup") release
; CHECK-NEXT:    store atomic i32 1, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 2) monotonic, align 4
; CHECK-NEXT:    fence syncscope("workgroup") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 3), align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(3) @lds
  fence syncscope("agent") release
  store atomic i32 1, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 2) monotonic, align 4
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 3)
  ret void
}

; A global access in the fenced region blocks narrowing.
define amdgpu_kernel void @no_narrow_global(ptr addrspace(1) %p) {
; CHECK-LABEL: @no_narrow_global(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") release
; CHECK-NEXT:    store atomic i32 1, ptr addrspace(3) @lds monotonic, align 4
; CHECK-NEXT:    fence syncscope("agent") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") release
  store atomic i32 1, ptr addrspace(3) @lds monotonic, align 4
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(3) @lds
  ret void
}

; A flat access may touch global memory and blocks narrowing.
define amdgpu_kernel void @no_narrow_flat(ptr %p) {
; CHECK-LABEL: @no_narrow_flat(
; CHECK-NEXT:    store i32 1, ptr [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") release
; CHECK-NEXT:    store atomic i32 1, ptr addrspace(3) @lds monotonic, align 4
; CHECK-NEXT:    fence syncscope("agent") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr %p
  fence syncscope("agent") release
  store atomic i32 1, ptr addrspace(3) @lds monotonic, align 4
  fence syncscope("agent") acquire
  %v = load i32, ptr %p
  store i32 %v, ptr addrspace(3) @lds
  ret void
}

; No accesses precede the fence in a kernel so the launch boundary covers it.
define amdgpu_kernel void @leading_fence_kernel(ptr addrspace(1) %p) {
; CHECK-LABEL: @leading_fence_kernel(
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; In a non kernel function the caller may have preceding accesses.
define void @leading_fence_func(ptr addrspace(1) %p) {
; CHECK-LABEL: @leading_fence_func(
; CHECK-NEXT:    fence syncscope("agent") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; No accesses follow the fence in a kernel so dispatch completion covers it.
define amdgpu_kernel void @trailing_fence_kernel(ptr addrspace(1) %p) {
; CHECK-LABEL: @trailing_fence_kernel(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") release
  ret void
}

; The join barrier covers the branch barriers on every path.
define amdgpu_kernel void @diamond_barriers(i1 %c, ptr addrspace(1) %out) {
; CHECK-LABEL: @diamond_barriers(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store i32 1, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    br i1 [[C:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       else:
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  store i32 1, ptr addrspace(3) @lds
  br i1 %c, label %then, label %else

then:
  call void @llvm.amdgcn.s.barrier()
  br label %join

else:
  call void @llvm.amdgcn.s.barrier()
  br label %join

join:
  call void @llvm.amdgcn.s.barrier()
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(1) %out
  ret void
}

; The barrier orders LDS accesses across loop iterations and must stay.
define amdgpu_kernel void @loop_barrier_lds(ptr addrspace(1) %out, i32 %n) {
; CHECK-LABEL: @loop_barrier_lds(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr [64 x i32], ptr addrspace(3) @lds, i32 0, i32 [[I]]
; CHECK-NEXT:    store i32 [[I]], ptr addrspace(3) [[GEP]], align 4
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    [[INC]] = add i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[INC]], [[N:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %inc, %loop ]
  %gep = getelementptr [64 x i32], ptr addrspace(3) @lds, i32 0, i32 %i
  store i32 %i, ptr addrspace(3) %gep
  call void @llvm.amdgcn.s.barrier()
  %inc = add i32 %i, 1
  %cmp = icmp ult i32 %inc, %n
  br i1 %cmp, label %loop, label %exit

exit:
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(1) %out
  ret void
}

; A fence in a loop with no shared accesses anywhere is removable.
define amdgpu_kernel void @loop_fence_no_access(i32 %n) {
; CHECK-LABEL: @loop_fence_no_access(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[INC]] = add i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[INC]], [[N:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %inc, %loop ]
  fence syncscope("agent") seq_cst
  %inc = add i32 %i, 1
  %cmp = icmp ult i32 %inc, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; An unknown call may access shared memory and keeps both fences.
define amdgpu_kernel void @call_blocks(ptr addrspace(1) %p) {
; CHECK-LABEL: @call_blocks(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    call void @ext()
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") seq_cst
  call void @ext()
  fence syncscope("agent") seq_cst
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; Private accesses are invisible to other threads so the covered fence goes.
define amdgpu_kernel void @private_between(ptr addrspace(1) %p) {
; CHECK-LABEL: @private_between(
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4, addrspace(5)
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    store i32 2, ptr addrspace(5) [[A]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  %a = alloca i32, align 4, addrspace(5)
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") seq_cst
  store i32 2, ptr addrspace(5) %a
  fence syncscope("agent") seq_cst
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; The one as fence is removed because the preceding full fence covers it.
; The mmra fence is removed because the following plain fence covers it.
; Both plain fences survive since an mmra fence is never a cover.
define amdgpu_kernel void @oneas_and_mmra(ptr addrspace(1) %p) {
; CHECK-LABEL: @oneas_and_mmra(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") seq_cst
  fence syncscope("agent-one-as") seq_cst
  %v = load i32, ptr addrspace(1) %p
  fence syncscope("agent") seq_cst, !mmra !0
  fence syncscope("agent") seq_cst
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; A one as fence does not cover a full fence.
define amdgpu_kernel void @oneas_no_cover(ptr addrspace(1) %p) {
; CHECK-LABEL: @oneas_no_cover(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent-one-as") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent-one-as") seq_cst
  %v = load i32, ptr addrspace(1) %p
  fence syncscope("agent-one-as") seq_cst
  fence syncscope("agent") seq_cst
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; Removal of the redundant barrier and release composes with narrowing of
; the surviving agent fences to workgroup scope.
define amdgpu_kernel void @remove_then_narrow() {
; CHECK-LABEL: @remove_then_narrow(
; CHECK-NEXT:    store i32 1, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    fence syncscope("workgroup") acquire
; CHECK-NEXT:    fence syncscope("workgroup") release
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    fence syncscope("workgroup") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 4), align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(3) @lds
  fence syncscope("agent") release
  call void @llvm.amdgcn.s.barrier()
  fence syncscope("agent") acquire
  fence syncscope("agent") release
  call void @llvm.amdgcn.s.barrier()
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 4)
  ret void
}

; Threads reach the rendezvous through different paths and the producer path
; stores to LDS before its barrier. The consumer barrier has an empty
; backward region yet must stay because kernel entry does not rendezvous
; waves.
define amdgpu_kernel void @wave_divergent_barriers(i1 %c, ptr addrspace(1) %out) {
; CHECK-LABEL: @wave_divergent_barriers(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[C:%.*]], label [[PRODUCER:%.*]], label [[CONSUMER:%.*]]
; CHECK:       producer:
; CHECK-NEXT:    store i32 42, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    br label [[JOIN:%.*]]
; CHECK:       consumer:
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %producer, label %consumer

producer:
  store i32 42, ptr addrspace(3) @lds
  call void @llvm.amdgcn.s.barrier()
  br label %join

consumer:
  call void @llvm.amdgcn.s.barrier()
  br label %join

join:
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(1) %out
  ret void
}

; A barrier is never removed by the kernel boundary rule even when no
; accesses surround it.
define amdgpu_kernel void @lone_barrier_kernel() {
; CHECK-LABEL: @lone_barrier_kernel(
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.barrier()
  ret void
}

; A barrier in a non kernel function has unknown surroundings in the caller.
define void @barrier_func() {
; CHECK-LABEL: @barrier_func(
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.barrier()
  ret void
}

; A GWS barrier is a cross workgroup rendezvous. A fence cover on the far
; side of it must not be honored.
define amdgpu_kernel void @gws_between(ptr addrspace(1) %p) {
; CHECK-LABEL: @gws_between(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    call void @llvm.amdgcn.ds.gws.barrier(i32 0, i32 0)
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") seq_cst
  call void @llvm.amdgcn.ds.gws.barrier(i32 0, i32 0)
  fence syncscope("agent") seq_cst
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; Graphics entry points have no dispatch packet synchronization so their
; boundaries are not covers.
define amdgpu_ps void @ps_leading_fence(ptr addrspace(1) %p) {
; CHECK-LABEL: @ps_leading_fence(
; CHECK-NEXT:    fence syncscope("agent") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

define amdgpu_ps void @ps_trailing_fence(ptr addrspace(1) %p) {
; CHECK-LABEL: @ps_trailing_fence(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") release
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") release
  ret void
}

; Acquire and release are mutually incomparable so neither adjacent fence
; covers the other.
define amdgpu_kernel void @release_acquire_adjacent(ptr addrspace(1) %p) {
; CHECK-LABEL: @release_acquire_adjacent(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") release
; CHECK-NEXT:    fence syncscope("agent") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") release
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; A wider scope covers a narrower one. The workgroup fence goes and the
; agent fence stays.
define amdgpu_kernel void @agent_covers_workgroup(ptr addrspace(1) %p) {
; CHECK-LABEL: @agent_covers_workgroup(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("workgroup") seq_cst
  fence syncscope("agent") seq_cst
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; seq_cst covers acq_rel but not the other way round. In each pair the
; weaker fence is removed and the stronger one survives.
define amdgpu_kernel void @seqcst_covers_acqrel(ptr addrspace(1) %p) {
; CHECK-LABEL: @seqcst_covers_acqrel(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") acq_rel
  fence syncscope("agent") seq_cst
  %v = load i32, ptr addrspace(1) %p
  fence syncscope("agent") seq_cst
  fence syncscope("agent") acq_rel
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; An unknown sync scope is neither a removal candidate nor a cover.
define amdgpu_kernel void @unknown_scope(ptr addrspace(1) %p) {
; CHECK-LABEL: @unknown_scope(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("foo") seq_cst
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("foo") seq_cst
  fence syncscope("agent") seq_cst
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}

; One as fences narrow to the workgroup one as scope.
define amdgpu_kernel void @narrow_oneas_lds_only() {
; CHECK-LABEL: @narrow_oneas_lds_only(
; CHECK-NEXT:    store i32 1, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    fence syncscope("workgroup-one-as") release
; CHECK-NEXT:    store atomic i32 1, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 2) monotonic, align 4
; CHECK-NEXT:    fence syncscope("workgroup-one-as") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 3), align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(3) @lds
  fence syncscope("agent-one-as") release
  store atomic i32 1, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 2) monotonic, align 4
  fence syncscope("agent-one-as") acquire
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 3)
  ret void
}

; A path ending in unreachable is covered even outside kernels.
define void @fence_then_unreachable(ptr addrspace(1) %p) {
; CHECK-LABEL: @fence_then_unreachable(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    unreachable
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") release
  unreachable
}

!0 = !{!"amdgpu-as", !"local"}
