; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -passes=amdgpu-optimize-barriers %s | FileCheck %s

@lds = internal addrspace(3) global [64 x i32] poison

; On subtargets with workgroup clusters LDS of one workgroup may be read from
; another so agent fences over LDS only regions must keep their scope.
define amdgpu_kernel void @no_narrow_lds_only_gfx1250() {
; CHECK-LABEL: @no_narrow_lds_only_gfx1250(
; CHECK-NEXT:    store i32 1, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    fence syncscope("agent") release
; CHECK-NEXT:    store atomic i32 1, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 2) monotonic, align 4
; CHECK-NEXT:    fence syncscope("agent") acquire
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(3) @lds, align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 3), align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(3) @lds
  fence syncscope("agent") release
  store atomic i32 1, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 2) monotonic, align 4
  fence syncscope("agent") acquire
  %v = load i32, ptr addrspace(3) @lds
  store i32 %v, ptr addrspace(3) getelementptr ([64 x i32], ptr addrspace(3) @lds, i32 0, i32 3)
  ret void
}

; Removal is still allowed. A fence covered by a stronger fence with no
; shared accesses between them stays redundant with clusters.
define amdgpu_kernel void @remove_still_allowed_gfx1250(ptr addrspace(1) %p) {
; CHECK-LABEL: @remove_still_allowed_gfx1250(
; CHECK-NEXT:    store i32 1, ptr addrspace(1) [[P:%.*]], align 4
; CHECK-NEXT:    fence syncscope("agent") seq_cst
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[P]], align 4
; CHECK-NEXT:    ret void
;
  store i32 1, ptr addrspace(1) %p
  fence syncscope("agent") seq_cst
  fence syncscope("agent") seq_cst
  %v = load i32, ptr addrspace(1) %p
  store i32 %v, ptr addrspace(1) %p
  ret void
}
