; RUN: llc -global-isel=0 < %s -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 | FileCheck %s

; Test that scalar FP4 (Float4E2M1FN) conversions generated by type
; legalization are fused into packed v_cvt_scalef32_pk_fp4_f32 HW
; instructions whenever pairs of nibble-sized results are OR'd into a
; wider integer output.
;
; Each v_cvt_scalef32_pk_fp4_f32 instruction can pack two f32 sources into
; a single 8-bit result, so the ideal count is ceil(N/2) for an <N x i4>
; output. The combine runs on ISD::OR nodes in performORCombine().

declare <2 x i4> @llvm.convert.to.arbitrary.fp.v2i4.v2f32(<2 x float>, metadata, metadata, i1)
declare <4 x i4> @llvm.convert.to.arbitrary.fp.v4i4.v4f32(<4 x float>, metadata, metadata, i1)
declare <8 x i4> @llvm.convert.to.arbitrary.fp.v8i4.v8f32(<8 x float>, metadata, metadata, i1)

; CHECK-LABEL: to_fp4_v2:
; CHECK-COUNT-1: v_cvt_scalef32_pk_fp4_f32
; CHECK-NOT:     v_cvt_scalef32_pk_fp4_f32
; CHECK:         s_setpc_b64
define i8 @to_fp4_v2(<2 x float> %x) {
  %r = call <2 x i4> @llvm.convert.to.arbitrary.fp.v2i4.v2f32(<2 x float> %x, metadata !"Float4E2M1FN", metadata !"round.tonearest", i1 false)
  %b = bitcast <2 x i4> %r to i8
  ret i8 %b
}

; CHECK-LABEL: to_fp4_v4:
; CHECK-COUNT-2: v_cvt_scalef32_pk_fp4_f32
; CHECK-NOT:     v_cvt_scalef32_pk_fp4_f32
; CHECK:         s_setpc_b64
define i16 @to_fp4_v4(<4 x float> %x) {
  %r = call <4 x i4> @llvm.convert.to.arbitrary.fp.v4i4.v4f32(<4 x float> %x, metadata !"Float4E2M1FN", metadata !"round.tonearest", i1 false)
  %b = bitcast <4 x i4> %r to i16
  ret i16 %b
}

; CHECK-LABEL: to_fp4_v8:
; CHECK-COUNT-4: v_cvt_scalef32_pk_fp4_f32
; CHECK-NOT:     v_cvt_scalef32_pk_fp4_f32
; CHECK:         s_setpc_b64
define i32 @to_fp4_v8(<8 x float> %x) {
  %r = call <8 x i4> @llvm.convert.to.arbitrary.fp.v8i4.v8f32(<8 x float> %x, metadata !"Float4E2M1FN", metadata !"round.tonearest", i1 false)
  %b = bitcast <8 x i4> %r to i32
  ret i32 %b
}
