; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1030 < %s | FileCheck %s

; gfx1030 stays scalar with or without the load saving and only pins the
; shared checks.

; Eight consecutive i8 weights are dequantized against a broadcast zero
; point and multiplied into an ordered fadd chain. The reductions are not
; profitable, so the four leading fsubs are offered as a standalone list.
; The scalar byte loads already coalesce into one dword load, so the
; vector load bundle saves nothing and the list must stay scalar.
define float @dequant8_ordered(ptr addrspace(1) %mat, ptr addrspace(1) %vec, half %zph, float %acc) {
; CHECK-LABEL: define float @dequant8_ordered(
; CHECK-SAME: ptr addrspace(1) [[MAT:%.*]], ptr addrspace(1) [[VEC:%.*]], half [[ZPH:%.*]], float [[ACC:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ZP:%.*]] = fpext half [[ZPH]] to float
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[V0:%.*]] = load half, ptr addrspace(1) [[VEC]], align 16
; CHECK-NEXT:    [[VP1:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[VEC]], i64 2
; CHECK-NEXT:    [[V1:%.*]] = load half, ptr addrspace(1) [[VP1]], align 2
; CHECK-NEXT:    [[VP2:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[VEC]], i64 4
; CHECK-NEXT:    [[V2:%.*]] = load half, ptr addrspace(1) [[VP2]], align 4
; CHECK-NEXT:    [[VP3:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[VEC]], i64 6
; CHECK-NEXT:    [[V3:%.*]] = load half, ptr addrspace(1) [[VP3]], align 2
; CHECK-NEXT:    [[VP4:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[VEC]], i64 8
; CHECK-NEXT:    [[V4:%.*]] = load half, ptr addrspace(1) [[VP4]], align 8
; CHECK-NEXT:    [[VP5:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[VEC]], i64 10
; CHECK-NEXT:    [[V5:%.*]] = load half, ptr addrspace(1) [[VP5]], align 2
; CHECK-NEXT:    [[VP6:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[VEC]], i64 12
; CHECK-NEXT:    [[V6:%.*]] = load half, ptr addrspace(1) [[VP6]], align 4
; CHECK-NEXT:    [[VP7:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[VEC]], i64 14
; CHECK-NEXT:    [[V7:%.*]] = load half, ptr addrspace(1) [[VP7]], align 2
; CHECK-NEXT:    [[Q0:%.*]] = load i8, ptr addrspace(1) [[MAT]], align 2
; CHECK-NEXT:    [[MP1:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[MAT]], i64 1
; CHECK-NEXT:    [[Q1:%.*]] = load i8, ptr addrspace(1) [[MP1]], align 1
; CHECK-NEXT:    [[MP2:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[MAT]], i64 2
; CHECK-NEXT:    [[Q2:%.*]] = load i8, ptr addrspace(1) [[MP2]], align 2
; CHECK-NEXT:    [[MP3:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[MAT]], i64 3
; CHECK-NEXT:    [[Q3:%.*]] = load i8, ptr addrspace(1) [[MP3]], align 1
; CHECK-NEXT:    [[MP4:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[MAT]], i64 4
; CHECK-NEXT:    [[Q4:%.*]] = load i8, ptr addrspace(1) [[MP4]], align 2
; CHECK-NEXT:    [[MP5:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[MAT]], i64 5
; CHECK-NEXT:    [[Q5:%.*]] = load i8, ptr addrspace(1) [[MP5]], align 1
; CHECK-NEXT:    [[MP6:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[MAT]], i64 6
; CHECK-NEXT:    [[Q6:%.*]] = load i8, ptr addrspace(1) [[MP6]], align 2
; CHECK-NEXT:    [[MP7:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[MAT]], i64 7
; CHECK-NEXT:    [[Q7:%.*]] = load i8, ptr addrspace(1) [[MP7]], align 1
; CHECK-NEXT:    [[X0:%.*]] = fpext half [[V0]] to float
; CHECK-NEXT:    [[F0:%.*]] = sitofp i8 [[Q0]] to float
; CHECK-NEXT:    [[D0:%.*]] = fsub contract float [[F0]], [[ZP]]
; CHECK-NEXT:    [[M0:%.*]] = fmul contract float [[D0]], [[X0]]
; CHECK-NEXT:    [[A0:%.*]] = fadd contract float [[ACC]], [[M0]]
; CHECK-NEXT:    [[X1:%.*]] = fpext half [[V1]] to float
; CHECK-NEXT:    [[F1:%.*]] = sitofp i8 [[Q1]] to float
; CHECK-NEXT:    [[D1:%.*]] = fsub contract float [[F1]], [[ZP]]
; CHECK-NEXT:    [[M1:%.*]] = fmul contract float [[D1]], [[X1]]
; CHECK-NEXT:    [[A1:%.*]] = fadd contract float [[A0]], [[M1]]
; CHECK-NEXT:    [[X2:%.*]] = fpext half [[V2]] to float
; CHECK-NEXT:    [[F2:%.*]] = sitofp i8 [[Q2]] to float
; CHECK-NEXT:    [[D2:%.*]] = fsub contract float [[F2]], [[ZP]]
; CHECK-NEXT:    [[M2:%.*]] = fmul contract float [[D2]], [[X2]]
; CHECK-NEXT:    [[A2:%.*]] = fadd contract float [[A1]], [[M2]]
; CHECK-NEXT:    [[X3:%.*]] = fpext half [[V3]] to float
; CHECK-NEXT:    [[F3:%.*]] = sitofp i8 [[Q3]] to float
; CHECK-NEXT:    [[D3:%.*]] = fsub contract float [[F3]], [[ZP]]
; CHECK-NEXT:    [[M3:%.*]] = fmul contract float [[D3]], [[X3]]
; CHECK-NEXT:    [[A3:%.*]] = fadd contract float [[A2]], [[M3]]
; CHECK-NEXT:    [[X4:%.*]] = fpext half [[V4]] to float
; CHECK-NEXT:    [[F4:%.*]] = sitofp i8 [[Q4]] to float
; CHECK-NEXT:    [[D4:%.*]] = fsub contract float [[F4]], [[ZP]]
; CHECK-NEXT:    [[M4:%.*]] = fmul contract float [[D4]], [[X4]]
; CHECK-NEXT:    [[A4:%.*]] = fadd contract float [[A3]], [[M4]]
; CHECK-NEXT:    [[X5:%.*]] = fpext half [[V5]] to float
; CHECK-NEXT:    [[F5:%.*]] = sitofp i8 [[Q5]] to float
; CHECK-NEXT:    [[D5:%.*]] = fsub contract float [[F5]], [[ZP]]
; CHECK-NEXT:    [[M5:%.*]] = fmul contract float [[D5]], [[X5]]
; CHECK-NEXT:    [[A5:%.*]] = fadd contract float [[A4]], [[M5]]
; CHECK-NEXT:    [[X6:%.*]] = fpext half [[V6]] to float
; CHECK-NEXT:    [[F6:%.*]] = sitofp i8 [[Q6]] to float
; CHECK-NEXT:    [[D6:%.*]] = fsub contract float [[F6]], [[ZP]]
; CHECK-NEXT:    [[M6:%.*]] = fmul contract float [[D6]], [[X6]]
; CHECK-NEXT:    [[A6:%.*]] = fadd contract float [[A5]], [[M6]]
; CHECK-NEXT:    [[X7:%.*]] = fpext half [[V7]] to float
; CHECK-NEXT:    [[F7:%.*]] = sitofp i8 [[Q7]] to float
; CHECK-NEXT:    [[D7:%.*]] = fsub contract float [[F7]], [[ZP]]
; CHECK-NEXT:    [[M7:%.*]] = fmul contract float [[D7]], [[X7]]
; CHECK-NEXT:    [[A7:%.*]] = fadd contract float [[A6]], [[M7]]
; CHECK-NEXT:    ret float [[A7]]
;
entry:
  %zp = fpext half %zph to float
  br label %body

body:
  %v0 = load half, ptr addrspace(1) %vec, align 16
  %vp1 = getelementptr inbounds i8, ptr addrspace(1) %vec, i64 2
  %v1 = load half, ptr addrspace(1) %vp1, align 2
  %vp2 = getelementptr inbounds i8, ptr addrspace(1) %vec, i64 4
  %v2 = load half, ptr addrspace(1) %vp2, align 4
  %vp3 = getelementptr inbounds i8, ptr addrspace(1) %vec, i64 6
  %v3 = load half, ptr addrspace(1) %vp3, align 2
  %vp4 = getelementptr inbounds i8, ptr addrspace(1) %vec, i64 8
  %v4 = load half, ptr addrspace(1) %vp4, align 8
  %vp5 = getelementptr inbounds i8, ptr addrspace(1) %vec, i64 10
  %v5 = load half, ptr addrspace(1) %vp5, align 2
  %vp6 = getelementptr inbounds i8, ptr addrspace(1) %vec, i64 12
  %v6 = load half, ptr addrspace(1) %vp6, align 4
  %vp7 = getelementptr inbounds i8, ptr addrspace(1) %vec, i64 14
  %v7 = load half, ptr addrspace(1) %vp7, align 2
  %q0 = load i8, ptr addrspace(1) %mat, align 2
  %mp1 = getelementptr inbounds i8, ptr addrspace(1) %mat, i64 1
  %q1 = load i8, ptr addrspace(1) %mp1, align 1
  %mp2 = getelementptr inbounds i8, ptr addrspace(1) %mat, i64 2
  %q2 = load i8, ptr addrspace(1) %mp2, align 2
  %mp3 = getelementptr inbounds i8, ptr addrspace(1) %mat, i64 3
  %q3 = load i8, ptr addrspace(1) %mp3, align 1
  %mp4 = getelementptr inbounds i8, ptr addrspace(1) %mat, i64 4
  %q4 = load i8, ptr addrspace(1) %mp4, align 2
  %mp5 = getelementptr inbounds i8, ptr addrspace(1) %mat, i64 5
  %q5 = load i8, ptr addrspace(1) %mp5, align 1
  %mp6 = getelementptr inbounds i8, ptr addrspace(1) %mat, i64 6
  %q6 = load i8, ptr addrspace(1) %mp6, align 2
  %mp7 = getelementptr inbounds i8, ptr addrspace(1) %mat, i64 7
  %q7 = load i8, ptr addrspace(1) %mp7, align 1
  %x0 = fpext half %v0 to float
  %f0 = sitofp i8 %q0 to float
  %d0 = fsub contract float %f0, %zp
  %m0 = fmul contract float %d0, %x0
  %a0 = fadd contract float %acc, %m0
  %x1 = fpext half %v1 to float
  %f1 = sitofp i8 %q1 to float
  %d1 = fsub contract float %f1, %zp
  %m1 = fmul contract float %d1, %x1
  %a1 = fadd contract float %a0, %m1
  %x2 = fpext half %v2 to float
  %f2 = sitofp i8 %q2 to float
  %d2 = fsub contract float %f2, %zp
  %m2 = fmul contract float %d2, %x2
  %a2 = fadd contract float %a1, %m2
  %x3 = fpext half %v3 to float
  %f3 = sitofp i8 %q3 to float
  %d3 = fsub contract float %f3, %zp
  %m3 = fmul contract float %d3, %x3
  %a3 = fadd contract float %a2, %m3
  %x4 = fpext half %v4 to float
  %f4 = sitofp i8 %q4 to float
  %d4 = fsub contract float %f4, %zp
  %m4 = fmul contract float %d4, %x4
  %a4 = fadd contract float %a3, %m4
  %x5 = fpext half %v5 to float
  %f5 = sitofp i8 %q5 to float
  %d5 = fsub contract float %f5, %zp
  %m5 = fmul contract float %d5, %x5
  %a5 = fadd contract float %a4, %m5
  %x6 = fpext half %v6 to float
  %f6 = sitofp i8 %q6 to float
  %d6 = fsub contract float %f6, %zp
  %m6 = fmul contract float %d6, %x6
  %a6 = fadd contract float %a5, %m6
  %x7 = fpext half %v7 to float
  %f7 = sitofp i8 %q7 to float
  %d7 = fsub contract float %f7, %zp
  %m7 = fmul contract float %d7, %x7
  %a7 = fadd contract float %a6, %m7
  ret float %a7
}

; A store chain over four converted bytes. The vector store and the
; conversion do not pay for themselves without the load saving.
define void @store4_sitofp(ptr addrspace(1) %in, ptr addrspace(1) %out) {
; CHECK-LABEL: define void @store4_sitofp(
; CHECK-SAME: ptr addrspace(1) [[IN:%.*]], ptr addrspace(1) [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[P1:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[IN]], i64 1
; CHECK-NEXT:    [[P2:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[IN]], i64 2
; CHECK-NEXT:    [[P3:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[IN]], i64 3
; CHECK-NEXT:    [[Q0:%.*]] = load i8, ptr addrspace(1) [[IN]], align 4
; CHECK-NEXT:    [[Q1:%.*]] = load i8, ptr addrspace(1) [[P1]], align 1
; CHECK-NEXT:    [[Q2:%.*]] = load i8, ptr addrspace(1) [[P2]], align 2
; CHECK-NEXT:    [[Q3:%.*]] = load i8, ptr addrspace(1) [[P3]], align 1
; CHECK-NEXT:    [[F0:%.*]] = sitofp i8 [[Q0]] to float
; CHECK-NEXT:    [[F1:%.*]] = sitofp i8 [[Q1]] to float
; CHECK-NEXT:    [[F2:%.*]] = sitofp i8 [[Q2]] to float
; CHECK-NEXT:    [[F3:%.*]] = sitofp i8 [[Q3]] to float
; CHECK-NEXT:    [[O1:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NEXT:    [[O2:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NEXT:    [[O3:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NEXT:    store float [[F0]], ptr addrspace(1) [[OUT]], align 16
; CHECK-NEXT:    store float [[F1]], ptr addrspace(1) [[O1]], align 4
; CHECK-NEXT:    store float [[F2]], ptr addrspace(1) [[O2]], align 8
; CHECK-NEXT:    store float [[F3]], ptr addrspace(1) [[O3]], align 4
; CHECK-NEXT:    ret void
;
  %p1 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 1
  %p2 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 2
  %p3 = getelementptr inbounds i8, ptr addrspace(1) %in, i64 3
  %q0 = load i8, ptr addrspace(1) %in, align 4
  %q1 = load i8, ptr addrspace(1) %p1, align 1
  %q2 = load i8, ptr addrspace(1) %p2, align 2
  %q3 = load i8, ptr addrspace(1) %p3, align 1
  %f0 = sitofp i8 %q0 to float
  %f1 = sitofp i8 %q1 to float
  %f2 = sitofp i8 %q2 to float
  %f3 = sitofp i8 %q3 to float
  %o1 = getelementptr inbounds float, ptr addrspace(1) %out, i64 1
  %o2 = getelementptr inbounds float, ptr addrspace(1) %out, i64 2
  %o3 = getelementptr inbounds float, ptr addrspace(1) %out, i64 3
  store float %f0, ptr addrspace(1) %out, align 16
  store float %f1, ptr addrspace(1) %o1, align 4
  store float %f2, ptr addrspace(1) %o2, align 8
  store float %f3, ptr addrspace(1) %o3, align 4
  ret void
}
