; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 < %s | FileCheck %s

; The scalar form of fma_chain_args is four v_fmac_f32: every fmul is folded
; into the fadd that consumes it. Vectorizing the multiplies breaks that, so
; the scalar side has to be priced as the fma chain it really is, not as four
; separate multiplies that no one would emit.

define void @fma_chain_args(ptr noalias %d, float %a0, float %a1, float %a2, float %a3, float %b0, float %b1, float %b2, float %b3, float %acc) {
; CHECK-LABEL: define void @fma_chain_args(
; CHECK-SAME: ptr noalias [[D:%.*]], float [[A0:%.*]], float [[A1:%.*]], float [[A2:%.*]], float [[A3:%.*]], float [[B0:%.*]], float [[B1:%.*]], float [[B2:%.*]], float [[B3:%.*]], float [[ACC:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M0:%.*]] = fmul contract float [[A0]], [[B0]]
; CHECK-NEXT:    [[M1:%.*]] = fmul contract float [[A1]], [[B1]]
; CHECK-NEXT:    [[M2:%.*]] = fmul contract float [[A2]], [[B2]]
; CHECK-NEXT:    [[M3:%.*]] = fmul contract float [[A3]], [[B3]]
; CHECK-NEXT:    [[S0:%.*]] = fadd contract float [[ACC]], [[M0]]
; CHECK-NEXT:    [[S1:%.*]] = fadd contract float [[S0]], [[M1]]
; CHECK-NEXT:    [[S2:%.*]] = fadd contract float [[S1]], [[M2]]
; CHECK-NEXT:    [[S3:%.*]] = fadd contract float [[S2]], [[M3]]
; CHECK-NEXT:    store float [[S3]], ptr [[D]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %m0 = fmul contract float %a0, %b0
  %m1 = fmul contract float %a1, %b1
  %m2 = fmul contract float %a2, %b2
  %m3 = fmul contract float %a3, %b3
  %s0 = fadd contract float %acc, %m0
  %s1 = fadd contract float %s0, %m1
  %s2 = fadd contract float %s1, %m2
  %s3 = fadd contract float %s2, %m3
  store float %s3, ptr %d, align 4
  ret void
}

; The adds here are an isomorphic bundle, so the vector form keeps the fusion
; and the multiplies must still be vectorized.

define void @axpy4(ptr noalias %d, ptr noalias %a, ptr noalias %b, ptr noalias %c) {
; CHECK-LABEL: define void @axpy4(
; CHECK-SAME: ptr noalias [[D:%.*]], ptr noalias [[A:%.*]], ptr noalias [[B:%.*]], ptr noalias [[C:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 2
; CHECK-NEXT:    [[B2:%.*]] = getelementptr inbounds float, ptr [[B]], i64 2
; CHECK-NEXT:    [[C2:%.*]] = getelementptr inbounds float, ptr [[C]], i64 2
; CHECK-NEXT:    [[D2:%.*]] = getelementptr inbounds float, ptr [[D]], i64 2
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x float>, ptr [[B]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = load <2 x float>, ptr [[C]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = fmul contract <2 x float> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP4:%.*]] = fadd contract <2 x float> [[TMP3]], [[TMP2]]
; CHECK-NEXT:    store <2 x float> [[TMP4]], ptr [[D]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = load <2 x float>, ptr [[A2]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = load <2 x float>, ptr [[B2]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = load <2 x float>, ptr [[C2]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = fmul contract <2 x float> [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP9:%.*]] = fadd contract <2 x float> [[TMP8]], [[TMP7]]
; CHECK-NEXT:    store <2 x float> [[TMP9]], ptr [[D2]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %a1 = getelementptr inbounds float, ptr %a, i64 1
  %a2 = getelementptr inbounds float, ptr %a, i64 2
  %a3 = getelementptr inbounds float, ptr %a, i64 3
  %b1 = getelementptr inbounds float, ptr %b, i64 1
  %b2 = getelementptr inbounds float, ptr %b, i64 2
  %b3 = getelementptr inbounds float, ptr %b, i64 3
  %c1 = getelementptr inbounds float, ptr %c, i64 1
  %c2 = getelementptr inbounds float, ptr %c, i64 2
  %c3 = getelementptr inbounds float, ptr %c, i64 3
  %d1 = getelementptr inbounds float, ptr %d, i64 1
  %d2 = getelementptr inbounds float, ptr %d, i64 2
  %d3 = getelementptr inbounds float, ptr %d, i64 3
  %a0v = load float, ptr %a, align 4
  %a1v = load float, ptr %a1, align 4
  %a2v = load float, ptr %a2, align 4
  %a3v = load float, ptr %a3, align 4
  %b0v = load float, ptr %b, align 4
  %b1v = load float, ptr %b1, align 4
  %b2v = load float, ptr %b2, align 4
  %b3v = load float, ptr %b3, align 4
  %c0v = load float, ptr %c, align 4
  %c1v = load float, ptr %c1, align 4
  %c2v = load float, ptr %c2, align 4
  %c3v = load float, ptr %c3, align 4
  %m0 = fmul contract float %a0v, %b0v
  %m1 = fmul contract float %a1v, %b1v
  %m2 = fmul contract float %a2v, %b2v
  %m3 = fmul contract float %a3v, %b3v
  %r0 = fadd contract float %m0, %c0v
  %r1 = fadd contract float %m1, %c1v
  %r2 = fadd contract float %m2, %c2v
  %r3 = fadd contract float %m3, %c3v
  store float %r0, ptr %d, align 4
  store float %r1, ptr %d1, align 4
  store float %r2, ptr %d2, align 4
  store float %r3, ptr %d3, align 4
  ret void
}
