; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1030 < %s | FileCheck %s

; Ordered contract fadd reduction over consecutive global loads. On AMDGPU
; the scalar loads coalesce into the same wide access a vector load would
; use, so the reduction must stay scalar and fuse into fmas.

target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

define amdgpu_kernel void @dotconv(ptr addrspace(1) noalias readonly align 4 %in, ptr addrspace(1) noalias readonly align 4 %mask, ptr addrspace(1) noalias writeonly align 4 %out) {
; CHECK-LABEL: define amdgpu_kernel void @dotconv(
; CHECK-SAME: ptr addrspace(1) noalias readonly align 4 [[IN:%.*]], ptr addrspace(1) noalias readonly align 4 [[MASK:%.*]], ptr addrspace(1) noalias writeonly align 4 [[OUT:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CALL_I:%.*]] = tail call i64 @_Z13get_global_idj(i32 noundef 0)
; CHECK-NEXT:    [[SEXT_I:%.*]] = shl i64 [[CALL_I]], 32
; CHECK-NEXT:    [[IDX_EXT_I:%.*]] = ashr exact i64 [[SEXT_I]], 32
; CHECK-NEXT:    [[ADD_PTR_I:%.*]] = getelementptr inbounds [4 x i8], ptr addrspace(1) [[IN]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr addrspace(1) [[ADD_PTR_I]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr addrspace(1) [[MASK]], align 4
; CHECK-NEXT:    [[MUL_I:%.*]] = fmul contract float [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[ADD_I:%.*]] = fadd contract float [[MUL_I]], 0.000000e+00
; CHECK-NEXT:    [[ARRAYIDX_I_1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 4
; CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 4
; CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_1]], align 4
; CHECK-NEXT:    [[MUL_I_1:%.*]] = fmul contract float [[TMP2]], [[TMP3]]
; CHECK-NEXT:    [[ADD_I_1:%.*]] = fadd contract float [[ADD_I]], [[MUL_I_1]]
; CHECK-NEXT:    [[ARRAYIDX_I_2:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 8
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_2:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 8
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_2]], align 4
; CHECK-NEXT:    [[MUL_I_2:%.*]] = fmul contract float [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[ADD_I_2:%.*]] = fadd contract float [[ADD_I_1]], [[MUL_I_2]]
; CHECK-NEXT:    [[ARRAYIDX_I_3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 12
; CHECK-NEXT:    [[TMP6:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 12
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_3]], align 4
; CHECK-NEXT:    [[MUL_I_3:%.*]] = fmul contract float [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[ADD_I_3:%.*]] = fadd contract float [[ADD_I_2]], [[MUL_I_3]]
; CHECK-NEXT:    [[ARRAYIDX_I_4:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 16
; CHECK-NEXT:    [[TMP8:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_4:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 16
; CHECK-NEXT:    [[TMP9:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_4]], align 4
; CHECK-NEXT:    [[MUL_I_4:%.*]] = fmul contract float [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[ADD_I_4:%.*]] = fadd contract float [[ADD_I_3]], [[MUL_I_4]]
; CHECK-NEXT:    [[ARRAYIDX_I_5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 20
; CHECK-NEXT:    [[TMP10:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 20
; CHECK-NEXT:    [[TMP11:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_5]], align 4
; CHECK-NEXT:    [[MUL_I_5:%.*]] = fmul contract float [[TMP10]], [[TMP11]]
; CHECK-NEXT:    [[ADD_I_5:%.*]] = fadd contract float [[ADD_I_4]], [[MUL_I_5]]
; CHECK-NEXT:    [[ARRAYIDX_I_6:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 24
; CHECK-NEXT:    [[TMP12:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_6:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 24
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_6]], align 4
; CHECK-NEXT:    [[MUL_I_6:%.*]] = fmul contract float [[TMP12]], [[TMP13]]
; CHECK-NEXT:    [[ADD_I_6:%.*]] = fadd contract float [[ADD_I_5]], [[MUL_I_6]]
; CHECK-NEXT:    [[ARRAYIDX_I_7:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 28
; CHECK-NEXT:    [[TMP14:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_7:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 28
; CHECK-NEXT:    [[TMP15:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_7]], align 4
; CHECK-NEXT:    [[MUL_I_7:%.*]] = fmul contract float [[TMP14]], [[TMP15]]
; CHECK-NEXT:    [[ADD_I_7:%.*]] = fadd contract float [[ADD_I_6]], [[MUL_I_7]]
; CHECK-NEXT:    [[ARRAYIDX_I_8:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 32
; CHECK-NEXT:    [[TMP16:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_8:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 32
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_8]], align 4
; CHECK-NEXT:    [[MUL_I_8:%.*]] = fmul contract float [[TMP16]], [[TMP17]]
; CHECK-NEXT:    [[ADD_I_8:%.*]] = fadd contract float [[ADD_I_7]], [[MUL_I_8]]
; CHECK-NEXT:    [[ARRAYIDX_I_9:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 36
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_9:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 36
; CHECK-NEXT:    [[TMP19:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_9]], align 4
; CHECK-NEXT:    [[MUL_I_9:%.*]] = fmul contract float [[TMP18]], [[TMP19]]
; CHECK-NEXT:    [[ADD_I_9:%.*]] = fadd contract float [[ADD_I_8]], [[MUL_I_9]]
; CHECK-NEXT:    [[ARRAYIDX_I_10:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 40
; CHECK-NEXT:    [[TMP20:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_10:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 40
; CHECK-NEXT:    [[TMP21:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_10]], align 4
; CHECK-NEXT:    [[MUL_I_10:%.*]] = fmul contract float [[TMP20]], [[TMP21]]
; CHECK-NEXT:    [[ADD_I_10:%.*]] = fadd contract float [[ADD_I_9]], [[MUL_I_10]]
; CHECK-NEXT:    [[ARRAYIDX_I_11:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 44
; CHECK-NEXT:    [[TMP22:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_11:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 44
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_11]], align 4
; CHECK-NEXT:    [[MUL_I_11:%.*]] = fmul contract float [[TMP22]], [[TMP23]]
; CHECK-NEXT:    [[ADD_I_11:%.*]] = fadd contract float [[ADD_I_10]], [[MUL_I_11]]
; CHECK-NEXT:    [[ARRAYIDX_I_12:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 48
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_12:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 48
; CHECK-NEXT:    [[TMP25:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_12]], align 4
; CHECK-NEXT:    [[MUL_I_12:%.*]] = fmul contract float [[TMP24]], [[TMP25]]
; CHECK-NEXT:    [[ADD_I_12:%.*]] = fadd contract float [[ADD_I_11]], [[MUL_I_12]]
; CHECK-NEXT:    [[ARRAYIDX_I_13:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 52
; CHECK-NEXT:    [[TMP26:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_13:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 52
; CHECK-NEXT:    [[TMP27:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_13]], align 4
; CHECK-NEXT:    [[MUL_I_13:%.*]] = fmul contract float [[TMP26]], [[TMP27]]
; CHECK-NEXT:    [[ADD_I_13:%.*]] = fadd contract float [[ADD_I_12]], [[MUL_I_13]]
; CHECK-NEXT:    [[ARRAYIDX_I_14:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 56
; CHECK-NEXT:    [[TMP28:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_14:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 56
; CHECK-NEXT:    [[TMP29:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_14]], align 4
; CHECK-NEXT:    [[MUL_I_14:%.*]] = fmul contract float [[TMP28]], [[TMP29]]
; CHECK-NEXT:    [[ADD_I_14:%.*]] = fadd contract float [[ADD_I_13]], [[MUL_I_14]]
; CHECK-NEXT:    [[ARRAYIDX_I_15:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[ADD_PTR_I]], i64 60
; CHECK-NEXT:    [[TMP30:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX_I_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX3_I_15:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(1) [[MASK]], i64 60
; CHECK-NEXT:    [[TMP31:%.*]] = load float, ptr addrspace(1) [[ARRAYIDX3_I_15]], align 4
; CHECK-NEXT:    [[MUL_I_15:%.*]] = fmul contract float [[TMP30]], [[TMP31]]
; CHECK-NEXT:    [[ADD_I_15:%.*]] = fadd contract float [[ADD_I_14]], [[MUL_I_15]]
; CHECK-NEXT:    [[ARRAYIDX5_I:%.*]] = getelementptr inbounds [4 x i8], ptr addrspace(1) [[OUT]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    store float [[ADD_I_15]], ptr addrspace(1) [[ARRAYIDX5_I]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %call.i = tail call i64 @_Z13get_global_idj(i32 noundef 0)
  %sext.i = shl i64 %call.i, 32
  %idx.ext.i = ashr exact i64 %sext.i, 32
  %add.ptr.i = getelementptr inbounds [4 x i8], ptr addrspace(1) %in, i64 %idx.ext.i
  %0 = load float, ptr addrspace(1) %add.ptr.i, align 4
  %1 = load float, ptr addrspace(1) %mask, align 4
  %mul.i = fmul contract float %0, %1
  %add.i = fadd contract float %mul.i, 0.000000e+00
  %arrayidx.i.1 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 4
  %2 = load float, ptr addrspace(1) %arrayidx.i.1, align 4
  %arrayidx3.i.1 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 4
  %3 = load float, ptr addrspace(1) %arrayidx3.i.1, align 4
  %mul.i.1 = fmul contract float %2, %3
  %add.i.1 = fadd contract float %add.i, %mul.i.1
  %arrayidx.i.2 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 8
  %4 = load float, ptr addrspace(1) %arrayidx.i.2, align 4
  %arrayidx3.i.2 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 8
  %5 = load float, ptr addrspace(1) %arrayidx3.i.2, align 4
  %mul.i.2 = fmul contract float %4, %5
  %add.i.2 = fadd contract float %add.i.1, %mul.i.2
  %arrayidx.i.3 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 12
  %6 = load float, ptr addrspace(1) %arrayidx.i.3, align 4
  %arrayidx3.i.3 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 12
  %7 = load float, ptr addrspace(1) %arrayidx3.i.3, align 4
  %mul.i.3 = fmul contract float %6, %7
  %add.i.3 = fadd contract float %add.i.2, %mul.i.3
  %arrayidx.i.4 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 16
  %8 = load float, ptr addrspace(1) %arrayidx.i.4, align 4
  %arrayidx3.i.4 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 16
  %9 = load float, ptr addrspace(1) %arrayidx3.i.4, align 4
  %mul.i.4 = fmul contract float %8, %9
  %add.i.4 = fadd contract float %add.i.3, %mul.i.4
  %arrayidx.i.5 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 20
  %10 = load float, ptr addrspace(1) %arrayidx.i.5, align 4
  %arrayidx3.i.5 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 20
  %11 = load float, ptr addrspace(1) %arrayidx3.i.5, align 4
  %mul.i.5 = fmul contract float %10, %11
  %add.i.5 = fadd contract float %add.i.4, %mul.i.5
  %arrayidx.i.6 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 24
  %12 = load float, ptr addrspace(1) %arrayidx.i.6, align 4
  %arrayidx3.i.6 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 24
  %13 = load float, ptr addrspace(1) %arrayidx3.i.6, align 4
  %mul.i.6 = fmul contract float %12, %13
  %add.i.6 = fadd contract float %add.i.5, %mul.i.6
  %arrayidx.i.7 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 28
  %14 = load float, ptr addrspace(1) %arrayidx.i.7, align 4
  %arrayidx3.i.7 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 28
  %15 = load float, ptr addrspace(1) %arrayidx3.i.7, align 4
  %mul.i.7 = fmul contract float %14, %15
  %add.i.7 = fadd contract float %add.i.6, %mul.i.7
  %arrayidx.i.8 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 32
  %16 = load float, ptr addrspace(1) %arrayidx.i.8, align 4
  %arrayidx3.i.8 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 32
  %17 = load float, ptr addrspace(1) %arrayidx3.i.8, align 4
  %mul.i.8 = fmul contract float %16, %17
  %add.i.8 = fadd contract float %add.i.7, %mul.i.8
  %arrayidx.i.9 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 36
  %18 = load float, ptr addrspace(1) %arrayidx.i.9, align 4
  %arrayidx3.i.9 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 36
  %19 = load float, ptr addrspace(1) %arrayidx3.i.9, align 4
  %mul.i.9 = fmul contract float %18, %19
  %add.i.9 = fadd contract float %add.i.8, %mul.i.9
  %arrayidx.i.10 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 40
  %20 = load float, ptr addrspace(1) %arrayidx.i.10, align 4
  %arrayidx3.i.10 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 40
  %21 = load float, ptr addrspace(1) %arrayidx3.i.10, align 4
  %mul.i.10 = fmul contract float %20, %21
  %add.i.10 = fadd contract float %add.i.9, %mul.i.10
  %arrayidx.i.11 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 44
  %22 = load float, ptr addrspace(1) %arrayidx.i.11, align 4
  %arrayidx3.i.11 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 44
  %23 = load float, ptr addrspace(1) %arrayidx3.i.11, align 4
  %mul.i.11 = fmul contract float %22, %23
  %add.i.11 = fadd contract float %add.i.10, %mul.i.11
  %arrayidx.i.12 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 48
  %24 = load float, ptr addrspace(1) %arrayidx.i.12, align 4
  %arrayidx3.i.12 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 48
  %25 = load float, ptr addrspace(1) %arrayidx3.i.12, align 4
  %mul.i.12 = fmul contract float %24, %25
  %add.i.12 = fadd contract float %add.i.11, %mul.i.12
  %arrayidx.i.13 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 52
  %26 = load float, ptr addrspace(1) %arrayidx.i.13, align 4
  %arrayidx3.i.13 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 52
  %27 = load float, ptr addrspace(1) %arrayidx3.i.13, align 4
  %mul.i.13 = fmul contract float %26, %27
  %add.i.13 = fadd contract float %add.i.12, %mul.i.13
  %arrayidx.i.14 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 56
  %28 = load float, ptr addrspace(1) %arrayidx.i.14, align 4
  %arrayidx3.i.14 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 56
  %29 = load float, ptr addrspace(1) %arrayidx3.i.14, align 4
  %mul.i.14 = fmul contract float %28, %29
  %add.i.14 = fadd contract float %add.i.13, %mul.i.14
  %arrayidx.i.15 = getelementptr inbounds nuw i8, ptr addrspace(1) %add.ptr.i, i64 60
  %30 = load float, ptr addrspace(1) %arrayidx.i.15, align 4
  %arrayidx3.i.15 = getelementptr inbounds nuw i8, ptr addrspace(1) %mask, i64 60
  %31 = load float, ptr addrspace(1) %arrayidx3.i.15, align 4
  %mul.i.15 = fmul contract float %30, %31
  %add.i.15 = fadd contract float %add.i.14, %mul.i.15
  %arrayidx5.i = getelementptr inbounds [4 x i8], ptr addrspace(1) %out, i64 %idx.ext.i
  store float %add.i.15, ptr addrspace(1) %arrayidx5.i, align 4
  ret void
}

declare i64 @_Z13get_global_idj(i32 noundef)
