; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a < %s | FileCheck %s --check-prefix=PACKED
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 < %s | FileCheck %s --check-prefix=PACKED
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 < %s | FileCheck %s --check-prefix=PACKED
; RUN: opt -passes=slp-vectorizer -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1030 < %s | FileCheck %s --check-prefix=SCALARFMA

; Reassociable fadd reduction over consecutive global loads. The scalar loads
; already coalesce into the wide access a vector load would use, so widening
; them buys no memory traffic, and a reduction that would trade an fma for
; that phantom saving is priced without it. A reduction with no fma at stake
; keeps its old pricing, so sum8 still vectorizes wherever it used to.

target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

define float @dot8(ptr addrspace(1) noalias readonly align 4 %a, ptr addrspace(1) noalias readonly align 4 %b) {
; PACKED-LABEL: define float @dot8(
; PACKED-SAME: ptr addrspace(1) noalias readonly align 4 [[A:%.*]], ptr addrspace(1) noalias readonly align 4 [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; PACKED-NEXT:  [[ENTRY:.*:]]
; PACKED-NEXT:    [[PA0:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 0
; PACKED-NEXT:    [[PB0:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 0
; PACKED-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr addrspace(1) [[PA0]], align 4
; PACKED-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr addrspace(1) [[PB0]], align 4
; PACKED-NEXT:    [[TMP2:%.*]] = fmul contract <4 x float> [[TMP0]], [[TMP1]]
; PACKED-NEXT:    [[PA4:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 4
; PACKED-NEXT:    [[PB4:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 4
; PACKED-NEXT:    [[TMP3:%.*]] = load <4 x float>, ptr addrspace(1) [[PA4]], align 4
; PACKED-NEXT:    [[TMP4:%.*]] = load <4 x float>, ptr addrspace(1) [[PB4]], align 4
; PACKED-NEXT:    [[TMP5:%.*]] = fmul contract <4 x float> [[TMP3]], [[TMP4]]
; PACKED-NEXT:    [[RDX_OP:%.*]] = fadd fast <4 x float> [[TMP2]], [[TMP5]]
; PACKED-NEXT:    [[TMP6:%.*]] = call fast float @llvm.vector.reduce.fadd.v4f32(float 0.000000e+00, <4 x float> [[RDX_OP]])
; PACKED-NEXT:    ret float [[TMP6]]
;
; SCALARFMA-LABEL: define float @dot8(
; SCALARFMA-SAME: ptr addrspace(1) noalias readonly align 4 [[A:%.*]], ptr addrspace(1) noalias readonly align 4 [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; SCALARFMA-NEXT:  [[ENTRY:.*:]]
; SCALARFMA-NEXT:    [[PA0:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 0
; SCALARFMA-NEXT:    [[LA0:%.*]] = load float, ptr addrspace(1) [[PA0]], align 4
; SCALARFMA-NEXT:    [[PB0:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 0
; SCALARFMA-NEXT:    [[LB0:%.*]] = load float, ptr addrspace(1) [[PB0]], align 4
; SCALARFMA-NEXT:    [[M0:%.*]] = fmul contract float [[LA0]], [[LB0]]
; SCALARFMA-NEXT:    [[PA1:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 1
; SCALARFMA-NEXT:    [[LA1:%.*]] = load float, ptr addrspace(1) [[PA1]], align 4
; SCALARFMA-NEXT:    [[PB1:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 1
; SCALARFMA-NEXT:    [[LB1:%.*]] = load float, ptr addrspace(1) [[PB1]], align 4
; SCALARFMA-NEXT:    [[M1:%.*]] = fmul contract float [[LA1]], [[LB1]]
; SCALARFMA-NEXT:    [[PA2:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 2
; SCALARFMA-NEXT:    [[LA2:%.*]] = load float, ptr addrspace(1) [[PA2]], align 4
; SCALARFMA-NEXT:    [[PB2:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 2
; SCALARFMA-NEXT:    [[LB2:%.*]] = load float, ptr addrspace(1) [[PB2]], align 4
; SCALARFMA-NEXT:    [[M2:%.*]] = fmul contract float [[LA2]], [[LB2]]
; SCALARFMA-NEXT:    [[PA3:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 3
; SCALARFMA-NEXT:    [[LA3:%.*]] = load float, ptr addrspace(1) [[PA3]], align 4
; SCALARFMA-NEXT:    [[PB3:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 3
; SCALARFMA-NEXT:    [[LB3:%.*]] = load float, ptr addrspace(1) [[PB3]], align 4
; SCALARFMA-NEXT:    [[M3:%.*]] = fmul contract float [[LA3]], [[LB3]]
; SCALARFMA-NEXT:    [[PA4:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 4
; SCALARFMA-NEXT:    [[LA4:%.*]] = load float, ptr addrspace(1) [[PA4]], align 4
; SCALARFMA-NEXT:    [[PB4:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 4
; SCALARFMA-NEXT:    [[LB4:%.*]] = load float, ptr addrspace(1) [[PB4]], align 4
; SCALARFMA-NEXT:    [[M4:%.*]] = fmul contract float [[LA4]], [[LB4]]
; SCALARFMA-NEXT:    [[PA5:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 5
; SCALARFMA-NEXT:    [[LA5:%.*]] = load float, ptr addrspace(1) [[PA5]], align 4
; SCALARFMA-NEXT:    [[PB5:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 5
; SCALARFMA-NEXT:    [[LB5:%.*]] = load float, ptr addrspace(1) [[PB5]], align 4
; SCALARFMA-NEXT:    [[M5:%.*]] = fmul contract float [[LA5]], [[LB5]]
; SCALARFMA-NEXT:    [[PA6:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 6
; SCALARFMA-NEXT:    [[LA6:%.*]] = load float, ptr addrspace(1) [[PA6]], align 4
; SCALARFMA-NEXT:    [[PB6:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 6
; SCALARFMA-NEXT:    [[LB6:%.*]] = load float, ptr addrspace(1) [[PB6]], align 4
; SCALARFMA-NEXT:    [[M6:%.*]] = fmul contract float [[LA6]], [[LB6]]
; SCALARFMA-NEXT:    [[PA7:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 7
; SCALARFMA-NEXT:    [[LA7:%.*]] = load float, ptr addrspace(1) [[PA7]], align 4
; SCALARFMA-NEXT:    [[PB7:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[B]], i64 7
; SCALARFMA-NEXT:    [[LB7:%.*]] = load float, ptr addrspace(1) [[PB7]], align 4
; SCALARFMA-NEXT:    [[M7:%.*]] = fmul contract float [[LA7]], [[LB7]]
; SCALARFMA-NEXT:    [[S1:%.*]] = fadd fast float [[M0]], [[M1]]
; SCALARFMA-NEXT:    [[S2:%.*]] = fadd fast float [[S1]], [[M2]]
; SCALARFMA-NEXT:    [[S3:%.*]] = fadd fast float [[S2]], [[M3]]
; SCALARFMA-NEXT:    [[S4:%.*]] = fadd fast float [[S3]], [[M4]]
; SCALARFMA-NEXT:    [[S5:%.*]] = fadd fast float [[S4]], [[M5]]
; SCALARFMA-NEXT:    [[S6:%.*]] = fadd fast float [[S5]], [[M6]]
; SCALARFMA-NEXT:    [[S7:%.*]] = fadd fast float [[S6]], [[M7]]
; SCALARFMA-NEXT:    ret float [[S7]]
;
entry:
  %pa0 = getelementptr inbounds float, ptr addrspace(1) %a, i64 0
  %la0 = load float, ptr addrspace(1) %pa0, align 4
  %pb0 = getelementptr inbounds float, ptr addrspace(1) %b, i64 0
  %lb0 = load float, ptr addrspace(1) %pb0, align 4
  %m0 = fmul contract float %la0, %lb0
  %pa1 = getelementptr inbounds float, ptr addrspace(1) %a, i64 1
  %la1 = load float, ptr addrspace(1) %pa1, align 4
  %pb1 = getelementptr inbounds float, ptr addrspace(1) %b, i64 1
  %lb1 = load float, ptr addrspace(1) %pb1, align 4
  %m1 = fmul contract float %la1, %lb1
  %pa2 = getelementptr inbounds float, ptr addrspace(1) %a, i64 2
  %la2 = load float, ptr addrspace(1) %pa2, align 4
  %pb2 = getelementptr inbounds float, ptr addrspace(1) %b, i64 2
  %lb2 = load float, ptr addrspace(1) %pb2, align 4
  %m2 = fmul contract float %la2, %lb2
  %pa3 = getelementptr inbounds float, ptr addrspace(1) %a, i64 3
  %la3 = load float, ptr addrspace(1) %pa3, align 4
  %pb3 = getelementptr inbounds float, ptr addrspace(1) %b, i64 3
  %lb3 = load float, ptr addrspace(1) %pb3, align 4
  %m3 = fmul contract float %la3, %lb3
  %pa4 = getelementptr inbounds float, ptr addrspace(1) %a, i64 4
  %la4 = load float, ptr addrspace(1) %pa4, align 4
  %pb4 = getelementptr inbounds float, ptr addrspace(1) %b, i64 4
  %lb4 = load float, ptr addrspace(1) %pb4, align 4
  %m4 = fmul contract float %la4, %lb4
  %pa5 = getelementptr inbounds float, ptr addrspace(1) %a, i64 5
  %la5 = load float, ptr addrspace(1) %pa5, align 4
  %pb5 = getelementptr inbounds float, ptr addrspace(1) %b, i64 5
  %lb5 = load float, ptr addrspace(1) %pb5, align 4
  %m5 = fmul contract float %la5, %lb5
  %pa6 = getelementptr inbounds float, ptr addrspace(1) %a, i64 6
  %la6 = load float, ptr addrspace(1) %pa6, align 4
  %pb6 = getelementptr inbounds float, ptr addrspace(1) %b, i64 6
  %lb6 = load float, ptr addrspace(1) %pb6, align 4
  %m6 = fmul contract float %la6, %lb6
  %pa7 = getelementptr inbounds float, ptr addrspace(1) %a, i64 7
  %la7 = load float, ptr addrspace(1) %pa7, align 4
  %pb7 = getelementptr inbounds float, ptr addrspace(1) %b, i64 7
  %lb7 = load float, ptr addrspace(1) %pb7, align 4
  %m7 = fmul contract float %la7, %lb7
  %s1 = fadd fast float %m0, %m1
  %s2 = fadd fast float %s1, %m2
  %s3 = fadd fast float %s2, %m3
  %s4 = fadd fast float %s3, %m4
  %s5 = fadd fast float %s4, %m5
  %s6 = fadd fast float %s5, %m6
  %s7 = fadd fast float %s6, %m7
  ret float %s7
}

define float @sum8(ptr addrspace(1) noalias readonly align 4 %a) {
; PACKED-LABEL: define float @sum8(
; PACKED-SAME: ptr addrspace(1) noalias readonly align 4 [[A:%.*]]) #[[ATTR0]] {
; PACKED-NEXT:  [[ENTRY:.*:]]
; PACKED-NEXT:    [[PA0:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 0
; PACKED-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr addrspace(1) [[PA0]], align 4
; PACKED-NEXT:    [[TMP1:%.*]] = call fast float @llvm.vector.reduce.fadd.v8f32(float 0.000000e+00, <8 x float> [[TMP0]])
; PACKED-NEXT:    ret float [[TMP1]]
;
; SCALARFMA-LABEL: define float @sum8(
; SCALARFMA-SAME: ptr addrspace(1) noalias readonly align 4 [[A:%.*]]) #[[ATTR0]] {
; SCALARFMA-NEXT:  [[ENTRY:.*:]]
; SCALARFMA-NEXT:    [[PA0:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 0
; SCALARFMA-NEXT:    [[LA0:%.*]] = load float, ptr addrspace(1) [[PA0]], align 4
; SCALARFMA-NEXT:    [[PA1:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 1
; SCALARFMA-NEXT:    [[LA1:%.*]] = load float, ptr addrspace(1) [[PA1]], align 4
; SCALARFMA-NEXT:    [[PA2:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 2
; SCALARFMA-NEXT:    [[LA2:%.*]] = load float, ptr addrspace(1) [[PA2]], align 4
; SCALARFMA-NEXT:    [[PA3:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 3
; SCALARFMA-NEXT:    [[LA3:%.*]] = load float, ptr addrspace(1) [[PA3]], align 4
; SCALARFMA-NEXT:    [[PA4:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 4
; SCALARFMA-NEXT:    [[LA4:%.*]] = load float, ptr addrspace(1) [[PA4]], align 4
; SCALARFMA-NEXT:    [[PA5:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 5
; SCALARFMA-NEXT:    [[LA5:%.*]] = load float, ptr addrspace(1) [[PA5]], align 4
; SCALARFMA-NEXT:    [[PA6:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 6
; SCALARFMA-NEXT:    [[LA6:%.*]] = load float, ptr addrspace(1) [[PA6]], align 4
; SCALARFMA-NEXT:    [[PA7:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[A]], i64 7
; SCALARFMA-NEXT:    [[LA7:%.*]] = load float, ptr addrspace(1) [[PA7]], align 4
; SCALARFMA-NEXT:    [[S1:%.*]] = fadd fast float [[LA0]], [[LA1]]
; SCALARFMA-NEXT:    [[S2:%.*]] = fadd fast float [[S1]], [[LA2]]
; SCALARFMA-NEXT:    [[S3:%.*]] = fadd fast float [[S2]], [[LA3]]
; SCALARFMA-NEXT:    [[S4:%.*]] = fadd fast float [[S3]], [[LA4]]
; SCALARFMA-NEXT:    [[S5:%.*]] = fadd fast float [[S4]], [[LA5]]
; SCALARFMA-NEXT:    [[S6:%.*]] = fadd fast float [[S5]], [[LA6]]
; SCALARFMA-NEXT:    [[S7:%.*]] = fadd fast float [[S6]], [[LA7]]
; SCALARFMA-NEXT:    ret float [[S7]]
;
entry:
  %pa0 = getelementptr inbounds float, ptr addrspace(1) %a, i64 0
  %la0 = load float, ptr addrspace(1) %pa0, align 4
  %pa1 = getelementptr inbounds float, ptr addrspace(1) %a, i64 1
  %la1 = load float, ptr addrspace(1) %pa1, align 4
  %pa2 = getelementptr inbounds float, ptr addrspace(1) %a, i64 2
  %la2 = load float, ptr addrspace(1) %pa2, align 4
  %pa3 = getelementptr inbounds float, ptr addrspace(1) %a, i64 3
  %la3 = load float, ptr addrspace(1) %pa3, align 4
  %pa4 = getelementptr inbounds float, ptr addrspace(1) %a, i64 4
  %la4 = load float, ptr addrspace(1) %pa4, align 4
  %pa5 = getelementptr inbounds float, ptr addrspace(1) %a, i64 5
  %la5 = load float, ptr addrspace(1) %pa5, align 4
  %pa6 = getelementptr inbounds float, ptr addrspace(1) %a, i64 6
  %la6 = load float, ptr addrspace(1) %pa6, align 4
  %pa7 = getelementptr inbounds float, ptr addrspace(1) %a, i64 7
  %la7 = load float, ptr addrspace(1) %pa7, align 4
  %s1 = fadd fast float %la0, %la1
  %s2 = fadd fast float %s1, %la2
  %s3 = fadd fast float %s2, %la3
  %s4 = fadd fast float %s3, %la4
  %s5 = fadd fast float %s4, %la5
  %s6 = fadd fast float %s5, %la6
  %s7 = fadd fast float %s6, %la7
  ret float %s7
}
