; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; Test llvm.convert.from.arbitrary intrinsic expansion.

declare float @llvm.convert.from.arbitrary.fp.f32.i8(i8, metadata)
declare float @llvm.convert.from.arbitrary.fp.f32.i6(i6, metadata)
declare float @llvm.convert.from.arbitrary.fp.f32.i4(i4, metadata)
declare <4 x float> @llvm.convert.from.arbitrary.fp.v4f32.v4i4(<4 x i4>, metadata)

declare half @llvm.convert.from.arbitrary.fp.f16.i8(i8, metadata)
declare double @llvm.convert.from.arbitrary.fp.f64.i8(i8, metadata)

; Float8E5M2
; Layout: sign(1) exp(5) mant(2), bias=15
; Supports: Inf, NaN, signed zero, denormals

; Float8E5M2 normal: 0_01111_00 = 1.0
define float @from_f8e5m2_normal() {
; CHECK-LABEL: from_f8e5m2_normal:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 60, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 zero: 0_00000_00 = +0.0
define float @from_f8e5m2_zero() {
; CHECK-LABEL: from_f8e5m2_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 negative zero: 1_00000_00 = -0.0
define float @from_f8e5m2_neg_zero() {
; CHECK-LABEL: from_f8e5m2_neg_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [-0.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -128, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 denorm: 0_00000_01 = 2^(-16)
define float @from_f8e5m2_denorm() {
; CHECK-LABEL: from_f8e5m2_denorm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.52587891E-5,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 1, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 +Inf: 0_11111_00
define float @from_f8e5m2_inf() {
; CHECK-LABEL: from_f8e5m2_inf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [+Inf,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 124, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 NaN: 0_11111_01
define float @from_f8e5m2_nan() {
; CHECK-LABEL: from_f8e5m2_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [NaN,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 125, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 max: 0_11110_11 = 57344
define float @from_f8e5m2_max() {
; CHECK-LABEL: from_f8e5m2_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [5.7344E+4,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 123, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 negative: 1_01111_00 = -1.0
define float @from_f8e5m2_neg() {
; CHECK-LABEL: from_f8e5m2_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -68, metadata !"Float8E5M2")
  ret float %r
}

; Float8E5M2 runtime arg test
define float @from_f8e5m2_dynamic(i8 %x) {
; CHECK-LABEL: from_f8e5m2_dynamic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset %rbx, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    movl %edi, %edx
; CHECK-NEXT:    shrl $2, %edx
; CHECK-NEXT:    andl $31, %edx
; CHECK-NEXT:    movl $-111, %r9d
; CHECK-NEXT:    subl %edx, %r9d
; CHECK-NEXT:    cmpl $31, %r9d
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %r9d, %ecx
; CHECK-NEXT:    movl %edi, %esi
; CHECK-NEXT:    andl $3, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shll $21, %r8d
; CHECK-NEXT:    leal 8388608(%r8), %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    andl $-128, %edi
; CHECK-NEXT:    shll $24, %edi
; CHECK-NEXT:    orl %edi, %eax
; CHECK-NEXT:    cmpl $25, %r9d
; CHECK-NEXT:    cmovael %edi, %eax
; CHECK-NEXT:    bsrl %esi, %r9d
; CHECK-NEXT:    movl %esi, %r10d
; CHECK-NEXT:    btcl %r9d, %r10d
; CHECK-NEXT:    xorl $31, %r9d
; CHECK-NEXT:    leal -8(%r9), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r10d
; CHECK-NEXT:    movl $142, %r11d
; CHECK-NEXT:    subl %r9d, %r11d
; CHECK-NEXT:    shll $23, %r11d
; CHECK-NEXT:    orl %edi, %r11d
; CHECK-NEXT:    orl %r10d, %r11d
; CHECK-NEXT:    leal 112(%rdx), %r9d
; CHECK-NEXT:    movl %r9d, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %edi, %ecx
; CHECK-NEXT:    orl %r8d, %ecx
; CHECK-NEXT:    testl %esi, %esi
; CHECK-NEXT:    sete %r8b
; CHECK-NEXT:    setne %sil
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    sete %r10b
; CHECK-NEXT:    testb %sil, %r10b
; CHECK-NEXT:    cmovnel %r11d, %ecx
; CHECK-NEXT:    cmpl $31, %edx
; CHECK-NEXT:    sete %dl
; CHECK-NEXT:    andb %dl, %sil
; CHECK-NEXT:    movl %esi, %r11d
; CHECK-NEXT:    xorb $1, %r11b
; CHECK-NEXT:    movl %r10d, %ebx
; CHECK-NEXT:    notb %bl
; CHECK-NEXT:    andb %r11b, %bl
; CHECK-NEXT:    leal 2139095040(%rdi), %r11d
; CHECK-NEXT:    cmpl $255, %r9d
; CHECK-NEXT:    setae %bpl
; CHECK-NEXT:    testb %bpl, %bl
; CHECK-NEXT:    cmovnel %r11d, %ecx
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    setle %r9b
; CHECK-NEXT:    testb %r9b, %bl
; CHECK-NEXT:    cmovnel %eax, %ecx
; CHECK-NEXT:    testb %r8b, %r10b
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    testb %r8b, %dl
; CHECK-NEXT:    cmovnel %r11d, %ecx
; CHECK-NEXT:    testb %sil, %sil
; CHECK-NEXT:    movl $2143289344, %eax # imm = 0x7FC00000
; CHECK-NEXT:    cmovel %ecx, %eax
; CHECK-NEXT:    movd %eax, %xmm0
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 %x, metadata !"Float8E5M2")
  ret float %r
}

; Float8E4M3FN (NanOnly, NanEncoding=AllOnes)
; Layout: sign(1) exp(4) mant(3), maxExp=8, minExp=-6, bias=7
; Only 0_1111_111 and 1_1111_111 are NaN; all other exp=15 values are finite.

; Float8E4M3FN normal: 0_0111_000 = 1.0
define float @from_f8e4m3fn_normal() {
; CHECK-LABEL: from_f8e4m3fn_normal:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 56, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN NaN: 0_1111_111
define float @from_f8e4m3fn_nan() {
; CHECK-LABEL: from_f8e4m3fn_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [NaN,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 127, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN not-NaN: 0_1111_110 = 448
; Despite exp=all-ones, this is a valid finite number (max value)
define float @from_f8e4m3fn_max() {
; CHECK-LABEL: from_f8e4m3fn_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [4.48E+2,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 126, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN not-NaN: 0_1111_101 = 416
; exp=all-ones but mant!=all-ones so this is finite
define float @from_f8e4m3fn_not_nan() {
; CHECK-LABEL: from_f8e4m3fn_not_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [4.16E+2,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 125, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN zero: 0_0000_000 = +0.0
define float @from_f8e4m3fn_zero() {
; CHECK-LABEL: from_f8e4m3fn_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN denorm: 0_0000_001 = 2^(-9)
define float @from_f8e4m3fn_denorm() {
; CHECK-LABEL: from_f8e4m3fn_denorm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.953125E-3,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 1, metadata !"Float8E4M3FN")
  ret float %r
}

; Float8E4M3FN runtime arg test
define float @from_f8e4m3fn_dynamic(i8 %x) {
; CHECK-LABEL: from_f8e4m3fn_dynamic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset %rbx, -16
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    movl %edi, %edx
; CHECK-NEXT:    shrl $3, %edx
; CHECK-NEXT:    andl $15, %edx
; CHECK-NEXT:    movl $-119, %r9d
; CHECK-NEXT:    subl %edx, %r9d
; CHECK-NEXT:    cmpl $31, %r9d
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %r9d, %ecx
; CHECK-NEXT:    movl %edi, %esi
; CHECK-NEXT:    andl $7, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shll $20, %r8d
; CHECK-NEXT:    leal 8388608(%r8), %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    andl $-128, %edi
; CHECK-NEXT:    shll $24, %edi
; CHECK-NEXT:    orl %edi, %eax
; CHECK-NEXT:    cmpl $25, %r9d
; CHECK-NEXT:    cmovael %edi, %eax
; CHECK-NEXT:    bsrl %esi, %r9d
; CHECK-NEXT:    movl %esi, %r10d
; CHECK-NEXT:    btcl %r9d, %r10d
; CHECK-NEXT:    xorl $31, %r9d
; CHECK-NEXT:    leal -8(%r9), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r10d
; CHECK-NEXT:    movl $149, %r11d
; CHECK-NEXT:    subl %r9d, %r11d
; CHECK-NEXT:    shll $23, %r11d
; CHECK-NEXT:    orl %edi, %r11d
; CHECK-NEXT:    orl %r10d, %r11d
; CHECK-NEXT:    leal 120(%rdx), %ecx
; CHECK-NEXT:    movl %ecx, %r9d
; CHECK-NEXT:    shll $23, %r9d
; CHECK-NEXT:    orl %edi, %r9d
; CHECK-NEXT:    orl %r8d, %r9d
; CHECK-NEXT:    testl %esi, %esi
; CHECK-NEXT:    sete %r8b
; CHECK-NEXT:    setne %r10b
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    sete %bl
; CHECK-NEXT:    testb %r10b, %bl
; CHECK-NEXT:    cmovnel %r11d, %r9d
; CHECK-NEXT:    cmpl $7, %esi
; CHECK-NEXT:    sete %sil
; CHECK-NEXT:    cmpl $15, %edx
; CHECK-NEXT:    sete %dl
; CHECK-NEXT:    andb %sil, %dl
; CHECK-NEXT:    movl %edx, %esi
; CHECK-NEXT:    xorb $1, %sil
; CHECK-NEXT:    movl %ebx, %r10d
; CHECK-NEXT:    notb %r10b
; CHECK-NEXT:    andb %sil, %r10b
; CHECK-NEXT:    leal 2139095040(%rdi), %esi
; CHECK-NEXT:    cmpl $255, %ecx
; CHECK-NEXT:    setae %r11b
; CHECK-NEXT:    testb %r11b, %r10b
; CHECK-NEXT:    cmovel %r9d, %esi
; CHECK-NEXT:    testl %ecx, %ecx
; CHECK-NEXT:    setle %cl
; CHECK-NEXT:    testb %cl, %r10b
; CHECK-NEXT:    cmovnel %eax, %esi
; CHECK-NEXT:    testb %r8b, %bl
; CHECK-NEXT:    cmovnel %edi, %esi
; CHECK-NEXT:    testb %dl, %dl
; CHECK-NEXT:    movl $2143289344, %eax # imm = 0x7FC00000
; CHECK-NEXT:    cmovel %esi, %eax
; CHECK-NEXT:    movd %eax, %xmm0
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 %x, metadata !"Float8E4M3FN")
  ret float %r
}

; Float6E3M2FN (FiniteOnly)
; Layout: sign(1) exp(3) mant(2), bias=3, maxExp=4
; No Inf, no NaN. All bit patterns are finite.

; Float6E3M2FN normal: 0_011_00 = 1.0
define float @from_f6e3m2fn_normal() {
; CHECK-LABEL: from_f6e3m2fn_normal:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 12, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN max: 0_111_11 = 28.0
define float @from_f6e3m2fn_max() {
; CHECK-LABEL: from_f6e3m2fn_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [2.8E+1,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 31, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN denorm: 0_000_01 = 0.0625
define float @from_f6e3m2fn_denorm() {
; CHECK-LABEL: from_f6e3m2fn_denorm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [6.25E-2,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 1, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN zero: 0_000_00 = +0.0
define float @from_f6e3m2fn_zero() {
; CHECK-LABEL: from_f6e3m2fn_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 0, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN negative: 1_011_00 = -1.0
define float @from_f6e3m2fn_neg() {
; CHECK-LABEL: from_f6e3m2fn_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 -20, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E3M2FN runtime arg test
define float @from_f6e3m2fn_dynamic(i6 %x) {
; CHECK-LABEL: from_f6e3m2fn_dynamic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    movl %edi, %edx
; CHECK-NEXT:    shrl $2, %edx
; CHECK-NEXT:    andl $7, %edx
; CHECK-NEXT:    movl $-123, %r9d
; CHECK-NEXT:    subl %edx, %r9d
; CHECK-NEXT:    cmpl $31, %r9d
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %r9d, %ecx
; CHECK-NEXT:    movl %edi, %esi
; CHECK-NEXT:    andl $3, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shll $21, %r8d
; CHECK-NEXT:    leal 8388608(%r8), %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    andl $-32, %edi
; CHECK-NEXT:    shll $26, %edi
; CHECK-NEXT:    orl %edi, %eax
; CHECK-NEXT:    cmpl $25, %r9d
; CHECK-NEXT:    cmovael %edi, %eax
; CHECK-NEXT:    bsrl %esi, %r9d
; CHECK-NEXT:    movl %esi, %r10d
; CHECK-NEXT:    btcl %r9d, %r10d
; CHECK-NEXT:    xorl $31, %r9d
; CHECK-NEXT:    leal -8(%r9), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r10d
; CHECK-NEXT:    movl $154, %ecx
; CHECK-NEXT:    subl %r9d, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %edi, %ecx
; CHECK-NEXT:    orl %r10d, %ecx
; CHECK-NEXT:    leal 124(%rdx), %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shll $23, %r10d
; CHECK-NEXT:    orl %edi, %r10d
; CHECK-NEXT:    orl %r8d, %r10d
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    setne %dl
; CHECK-NEXT:    sete %r8b
; CHECK-NEXT:    testl %esi, %esi
; CHECK-NEXT:    sete %sil
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    testb %r11b, %r8b
; CHECK-NEXT:    cmovnel %ecx, %r10d
; CHECK-NEXT:    leal 2139095040(%rdi), %ecx
; CHECK-NEXT:    cmpl $255, %r9d
; CHECK-NEXT:    setae %r11b
; CHECK-NEXT:    testb %r11b, %dl
; CHECK-NEXT:    cmovel %r10d, %ecx
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    setle %r9b
; CHECK-NEXT:    testb %r9b, %dl
; CHECK-NEXT:    cmovnel %eax, %ecx
; CHECK-NEXT:    testb %sil, %r8b
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    movd %ecx, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 %x, metadata !"Float6E3M2FN")
  ret float %r
}

; Float6E2M3FN (FiniteOnly)
; Layout: sign(1) exp(2) mant(3), bias=1, maxExp=2
; No Inf, no NaN. All bit patterns are finite.

; Float6E2M3FN normal: 0_01_000 = 1.0
define float @from_f6e2m3fn_normal() {
; CHECK-LABEL: from_f6e2m3fn_normal:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 8, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN max: 0_11_111 = 7.5
define float @from_f6e2m3fn_max() {
; CHECK-LABEL: from_f6e2m3fn_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [7.5E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 31, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN denorm: 0_00_001 = 0.125
define float @from_f6e2m3fn_denorm() {
; CHECK-LABEL: from_f6e2m3fn_denorm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.25E-1,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 1, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN zero: 0_00_000 = +0.0
define float @from_f6e2m3fn_zero() {
; CHECK-LABEL: from_f6e2m3fn_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 0, metadata !"Float6E2M3FN")
  ret float %r
}

; Float6E2M3FN runtime arg test
define float @from_f6e2m3fn_dynamic(i6 %x) {
; CHECK-LABEL: from_f6e2m3fn_dynamic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    movl %edi, %edx
; CHECK-NEXT:    shrl $3, %edx
; CHECK-NEXT:    andl $3, %edx
; CHECK-NEXT:    movl %edx, %r9d
; CHECK-NEXT:    xorl $-125, %r9d
; CHECK-NEXT:    cmpl $31, %r9d
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %r9d, %ecx
; CHECK-NEXT:    movl %edi, %esi
; CHECK-NEXT:    andl $7, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shll $20, %r8d
; CHECK-NEXT:    leal 8388608(%r8), %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    andl $-32, %edi
; CHECK-NEXT:    shll $26, %edi
; CHECK-NEXT:    orl %edi, %eax
; CHECK-NEXT:    cmpl $25, %r9d
; CHECK-NEXT:    cmovael %edi, %eax
; CHECK-NEXT:    bsrl %esi, %r9d
; CHECK-NEXT:    movl %esi, %r10d
; CHECK-NEXT:    btcl %r9d, %r10d
; CHECK-NEXT:    xorl $31, %r9d
; CHECK-NEXT:    leal -8(%r9), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r10d
; CHECK-NEXT:    movl $155, %ecx
; CHECK-NEXT:    subl %r9d, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %edi, %ecx
; CHECK-NEXT:    orl %r10d, %ecx
; CHECK-NEXT:    leal 126(%rdx), %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shll $23, %r10d
; CHECK-NEXT:    orl %edi, %r10d
; CHECK-NEXT:    orl %r8d, %r10d
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    setne %dl
; CHECK-NEXT:    sete %r8b
; CHECK-NEXT:    testl %esi, %esi
; CHECK-NEXT:    sete %sil
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    testb %r11b, %r8b
; CHECK-NEXT:    cmovnel %ecx, %r10d
; CHECK-NEXT:    leal 2139095040(%rdi), %ecx
; CHECK-NEXT:    cmpl $255, %r9d
; CHECK-NEXT:    setae %r11b
; CHECK-NEXT:    testb %r11b, %dl
; CHECK-NEXT:    cmovel %r10d, %ecx
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    setle %r9b
; CHECK-NEXT:    testb %r9b, %dl
; CHECK-NEXT:    cmovnel %eax, %ecx
; CHECK-NEXT:    testb %sil, %r8b
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    movd %ecx, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i6(i6 %x, metadata !"Float6E2M3FN")
  ret float %r
}

; Float4E2M1FN (FiniteOnly)
; Layout: sign(1) exp(2) mant(1), bias=1, maxExp=2
; No Inf, no NaN.

; Float4E2M1FN normal: 0_01_0 = 1.0
define float @from_f4e2m1fn_normal() {
; CHECK-LABEL: from_f4e2m1fn_normal:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 2, metadata !"Float4E2M1FN")
  ret float %r
}

; Float4E2M1FN denorm: 0_00_1 = 0.5
define float @from_f4e2m1fn_denorm() {
; CHECK-LABEL: from_f4e2m1fn_denorm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [5.0E-1,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 1, metadata !"Float4E2M1FN")
  ret float %r
}

; Float4E2M1FN max: 0_11_1 = 6.0
define float @from_f4e2m1fn_max() {
; CHECK-LABEL: from_f4e2m1fn_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [6.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 7, metadata !"Float4E2M1FN")
  ret float %r
}

; Float4E2M1FN runtime arg test
define float @from_f4e2m1fn_dynamic(i4 %x) {
; CHECK-LABEL: from_f4e2m1fn_dynamic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    movl %edi, %edx
; CHECK-NEXT:    shrl %edx
; CHECK-NEXT:    andl $3, %edx
; CHECK-NEXT:    movl %edx, %r9d
; CHECK-NEXT:    xorl $-125, %r9d
; CHECK-NEXT:    cmpl $31, %r9d
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %r9d, %ecx
; CHECK-NEXT:    movl %edi, %esi
; CHECK-NEXT:    andl $1, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shll $22, %r8d
; CHECK-NEXT:    leal 8388608(%r8), %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    andl $-8, %edi
; CHECK-NEXT:    shll $28, %edi
; CHECK-NEXT:    orl %edi, %eax
; CHECK-NEXT:    cmpl $25, %r9d
; CHECK-NEXT:    cmovael %edi, %eax
; CHECK-NEXT:    bsrl %esi, %r9d
; CHECK-NEXT:    movl %esi, %r10d
; CHECK-NEXT:    btcl %r9d, %r10d
; CHECK-NEXT:    xorl $31, %r9d
; CHECK-NEXT:    leal -8(%r9), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r10d
; CHECK-NEXT:    movl $157, %ecx
; CHECK-NEXT:    subl %r9d, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %edi, %ecx
; CHECK-NEXT:    orl %r10d, %ecx
; CHECK-NEXT:    leal 126(%rdx), %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shll $23, %r10d
; CHECK-NEXT:    orl %edi, %r10d
; CHECK-NEXT:    orl %r8d, %r10d
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    setne %dl
; CHECK-NEXT:    sete %r8b
; CHECK-NEXT:    testl %esi, %esi
; CHECK-NEXT:    sete %sil
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    testb %r11b, %r8b
; CHECK-NEXT:    cmovnel %ecx, %r10d
; CHECK-NEXT:    leal 2139095040(%rdi), %ecx
; CHECK-NEXT:    cmpl $255, %r9d
; CHECK-NEXT:    setae %r11b
; CHECK-NEXT:    testb %r11b, %dl
; CHECK-NEXT:    cmovel %r10d, %ecx
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    setle %r9b
; CHECK-NEXT:    testb %r9b, %dl
; CHECK-NEXT:    cmovnel %eax, %ecx
; CHECK-NEXT:    testb %sil, %r8b
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    movd %ecx, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i4(i4 %x, metadata !"Float4E2M1FN")
  ret float %r
}

; Float8E5M2 to f16: 1.0
define half @from_f8e5m2_to_f16() {
; CHECK-LABEL: from_f8e5m2_to_f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %r = call half @llvm.convert.from.arbitrary.fp.f16.i8(i8 60, metadata !"Float8E5M2")
  ret half %r
}

; Float8E5M2 to f64: 1.0
define double @from_f8e5m2_to_f64() {
; CHECK-LABEL: from_f8e5m2_to_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movsd {{.*#+}} xmm0 = [1.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call double @llvm.convert.from.arbitrary.fp.f64.i8(i8 60, metadata !"Float8E5M2")
  ret double %r
}

declare bfloat @llvm.convert.from.arbitrary.fp.bf16.i8(i8, metadata)

; Float8E5M2 to bf16: 1.0
; bf16 has: sign(1) exp(8) mant(7), bias=127
define bfloat @from_f8e5m2_to_bf16() {
; CHECK-LABEL: from_f8e5m2_to_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    callq __truncsfbf2@PLT
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call bfloat @llvm.convert.from.arbitrary.fp.bf16.i8(i8 60, metadata !"Float8E5M2")
  ret bfloat %r
}

; Vector test: Float4E2M1FN <4 x i4> -> <4 x float>
define <4 x float> @fp4_to_f32_vec(<4 x i4> %x) {
; CHECK-LABEL: fp4_to_f32_vec:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    .cfi_offset %rbx, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[3,3,3,3]
; CHECK-NEXT:    movd %xmm1, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shrl %r8d
; CHECK-NEXT:    andl $3, %r8d
; CHECK-NEXT:    movl %r8d, %edx
; CHECK-NEXT:    xorl $-125, %edx
; CHECK-NEXT:    cmpl $31, %edx
; CHECK-NEXT:    movl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %edx, %ecx
; CHECK-NEXT:    movl %esi, %r9d
; CHECK-NEXT:    andl $1, %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shll $22, %r10d
; CHECK-NEXT:    leal 8388608(%r10), %edi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    andl $-8, %esi
; CHECK-NEXT:    shll $28, %esi
; CHECK-NEXT:    orl %esi, %edi
; CHECK-NEXT:    cmpl $25, %edx
; CHECK-NEXT:    cmovael %esi, %edi
; CHECK-NEXT:    bsrl %r9d, %r11d
; CHECK-NEXT:    movl %r9d, %ebx
; CHECK-NEXT:    btcl %r11d, %ebx
; CHECK-NEXT:    xorl $31, %r11d
; CHECK-NEXT:    leal -8(%r11), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %ebx
; CHECK-NEXT:    movl $157, %edx
; CHECK-NEXT:    movl $157, %ecx
; CHECK-NEXT:    subl %r11d, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %esi, %ecx
; CHECK-NEXT:    orl %ebx, %ecx
; CHECK-NEXT:    leal 126(%r8), %r11d
; CHECK-NEXT:    movl %r11d, %ebx
; CHECK-NEXT:    shll $23, %ebx
; CHECK-NEXT:    orl %esi, %ebx
; CHECK-NEXT:    orl %r10d, %ebx
; CHECK-NEXT:    testl %r8d, %r8d
; CHECK-NEXT:    setne %r8b
; CHECK-NEXT:    sete %r10b
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    sete %r9b
; CHECK-NEXT:    setne %bpl
; CHECK-NEXT:    testb %bpl, %r10b
; CHECK-NEXT:    cmovnel %ecx, %ebx
; CHECK-NEXT:    leal 2139095040(%rsi), %ecx
; CHECK-NEXT:    cmpl $255, %r11d
; CHECK-NEXT:    setae %bpl
; CHECK-NEXT:    testb %bpl, %r8b
; CHECK-NEXT:    cmovel %ebx, %ecx
; CHECK-NEXT:    testl %r11d, %r11d
; CHECK-NEXT:    setle %r11b
; CHECK-NEXT:    testb %r11b, %r8b
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    testb %r9b, %r10b
; CHECK-NEXT:    cmovnel %esi, %ecx
; CHECK-NEXT:    movd %ecx, %xmm1
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm0[2,3,2,3]
; CHECK-NEXT:    movd %xmm2, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shrl %r8d
; CHECK-NEXT:    andl $3, %r8d
; CHECK-NEXT:    movl %r8d, %r11d
; CHECK-NEXT:    xorl $-125, %r11d
; CHECK-NEXT:    cmpl $31, %r11d
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %r11d, %ecx
; CHECK-NEXT:    movl %esi, %r9d
; CHECK-NEXT:    andl $1, %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shll $22, %r10d
; CHECK-NEXT:    leal 8388608(%r10), %edi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    andl $-8, %esi
; CHECK-NEXT:    shll $28, %esi
; CHECK-NEXT:    orl %esi, %edi
; CHECK-NEXT:    cmpl $25, %r11d
; CHECK-NEXT:    cmovael %esi, %edi
; CHECK-NEXT:    bsrl %r9d, %r11d
; CHECK-NEXT:    movl %r9d, %ebx
; CHECK-NEXT:    btcl %r11d, %ebx
; CHECK-NEXT:    xorl $31, %r11d
; CHECK-NEXT:    leal -8(%r11), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %ebx
; CHECK-NEXT:    movl $157, %ecx
; CHECK-NEXT:    subl %r11d, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %esi, %ecx
; CHECK-NEXT:    orl %ebx, %ecx
; CHECK-NEXT:    leal 126(%r8), %r11d
; CHECK-NEXT:    movl %r11d, %ebx
; CHECK-NEXT:    shll $23, %ebx
; CHECK-NEXT:    orl %esi, %ebx
; CHECK-NEXT:    orl %r10d, %ebx
; CHECK-NEXT:    testl %r8d, %r8d
; CHECK-NEXT:    setne %r8b
; CHECK-NEXT:    sete %r10b
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    sete %r9b
; CHECK-NEXT:    setne %bpl
; CHECK-NEXT:    testb %bpl, %r10b
; CHECK-NEXT:    cmovnel %ecx, %ebx
; CHECK-NEXT:    leal 2139095040(%rsi), %ecx
; CHECK-NEXT:    cmpl $255, %r11d
; CHECK-NEXT:    setae %bpl
; CHECK-NEXT:    testb %bpl, %r8b
; CHECK-NEXT:    cmovel %ebx, %ecx
; CHECK-NEXT:    testl %r11d, %r11d
; CHECK-NEXT:    setle %r11b
; CHECK-NEXT:    testb %r11b, %r8b
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    testb %r9b, %r10b
; CHECK-NEXT:    cmovnel %esi, %ecx
; CHECK-NEXT:    movd %ecx, %xmm2
; CHECK-NEXT:    punpckldq {{.*#+}} xmm2 = xmm2[0],xmm1[0],xmm2[1],xmm1[1]
; CHECK-NEXT:    movd %xmm0, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shrl %r8d
; CHECK-NEXT:    andl $3, %r8d
; CHECK-NEXT:    movl %r8d, %r11d
; CHECK-NEXT:    xorl $-125, %r11d
; CHECK-NEXT:    cmpl $31, %r11d
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %r11d, %ecx
; CHECK-NEXT:    movl %esi, %r9d
; CHECK-NEXT:    andl $1, %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shll $22, %r10d
; CHECK-NEXT:    leal 8388608(%r10), %edi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    andl $-8, %esi
; CHECK-NEXT:    shll $28, %esi
; CHECK-NEXT:    orl %esi, %edi
; CHECK-NEXT:    cmpl $25, %r11d
; CHECK-NEXT:    cmovael %esi, %edi
; CHECK-NEXT:    bsrl %r9d, %r11d
; CHECK-NEXT:    movl %r9d, %ebx
; CHECK-NEXT:    btcl %r11d, %ebx
; CHECK-NEXT:    xorl $31, %r11d
; CHECK-NEXT:    leal -8(%r11), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %ebx
; CHECK-NEXT:    movl $157, %ecx
; CHECK-NEXT:    subl %r11d, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %esi, %ecx
; CHECK-NEXT:    orl %ebx, %ecx
; CHECK-NEXT:    leal 126(%r8), %r11d
; CHECK-NEXT:    movl %r11d, %ebx
; CHECK-NEXT:    shll $23, %ebx
; CHECK-NEXT:    orl %esi, %ebx
; CHECK-NEXT:    orl %r10d, %ebx
; CHECK-NEXT:    testl %r8d, %r8d
; CHECK-NEXT:    setne %r8b
; CHECK-NEXT:    sete %r10b
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    sete %r9b
; CHECK-NEXT:    setne %bpl
; CHECK-NEXT:    testb %bpl, %r10b
; CHECK-NEXT:    cmovnel %ecx, %ebx
; CHECK-NEXT:    leal 2139095040(%rsi), %ecx
; CHECK-NEXT:    cmpl $255, %r11d
; CHECK-NEXT:    setae %bpl
; CHECK-NEXT:    testb %bpl, %r8b
; CHECK-NEXT:    cmovel %ebx, %ecx
; CHECK-NEXT:    testl %r11d, %r11d
; CHECK-NEXT:    setle %r11b
; CHECK-NEXT:    testb %r11b, %r8b
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    testb %r9b, %r10b
; CHECK-NEXT:    cmovnel %esi, %ecx
; CHECK-NEXT:    movd %ecx, %xmm1
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movd %xmm0, %esi
; CHECK-NEXT:    movl %esi, %r8d
; CHECK-NEXT:    shrl %r8d
; CHECK-NEXT:    andl $3, %r8d
; CHECK-NEXT:    movl %r8d, %r11d
; CHECK-NEXT:    xorl $-125, %r11d
; CHECK-NEXT:    cmpl $31, %r11d
; CHECK-NEXT:    cmovbl %r11d, %eax
; CHECK-NEXT:    movl %esi, %r9d
; CHECK-NEXT:    andl $1, %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shll $22, %r10d
; CHECK-NEXT:    leal 8388608(%r10), %edi
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    andl $-8, %esi
; CHECK-NEXT:    shll $28, %esi
; CHECK-NEXT:    orl %esi, %edi
; CHECK-NEXT:    cmpl $25, %r11d
; CHECK-NEXT:    cmovael %esi, %edi
; CHECK-NEXT:    bsrl %r9d, %eax
; CHECK-NEXT:    movl %r9d, %r11d
; CHECK-NEXT:    btcl %eax, %r11d
; CHECK-NEXT:    xorl $31, %eax
; CHECK-NEXT:    leal -8(%rax), %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r11d
; CHECK-NEXT:    subl %eax, %edx
; CHECK-NEXT:    shll $23, %edx
; CHECK-NEXT:    orl %esi, %edx
; CHECK-NEXT:    orl %r11d, %edx
; CHECK-NEXT:    leal 126(%r8), %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    orl %esi, %ecx
; CHECK-NEXT:    orl %r10d, %ecx
; CHECK-NEXT:    testl %r8d, %r8d
; CHECK-NEXT:    setne %r8b
; CHECK-NEXT:    sete %r10b
; CHECK-NEXT:    testl %r9d, %r9d
; CHECK-NEXT:    sete %r9b
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    testb %r11b, %r10b
; CHECK-NEXT:    cmovnel %edx, %ecx
; CHECK-NEXT:    leal 2139095040(%rsi), %edx
; CHECK-NEXT:    cmpl $255, %eax
; CHECK-NEXT:    setae %r11b
; CHECK-NEXT:    testb %r11b, %r8b
; CHECK-NEXT:    cmovel %ecx, %edx
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    setle %al
; CHECK-NEXT:    testb %al, %r8b
; CHECK-NEXT:    cmovnel %edi, %edx
; CHECK-NEXT:    testb %r9b, %r10b
; CHECK-NEXT:    cmovnel %esi, %edx
; CHECK-NEXT:    movd %edx, %xmm0
; CHECK-NEXT:    punpckldq {{.*#+}} xmm1 = xmm1[0],xmm0[0],xmm1[1],xmm0[1]
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm2[0]
; CHECK-NEXT:    movdqa %xmm1, %xmm0
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <4 x float> @llvm.convert.from.arbitrary.fp.v4f32.v4i4(<4 x i4> %x, metadata !"Float4E2M1FN")
  ret <4 x float> %r
}
