; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; Test llvm.convert.{from,to}.arbitrary.fp expansion for the FNUZ family:
;   Float8E5M2FNUZ, Float8E4M3FNUZ, Float8E4M3B11FNUZ.
;
; FNUZ semantics:
;   - Bias offset is +1 vs the FN equivalent (e.g. E4M3FNUZ bias 8, E4M3FN 7).
;   - Single zero encoding (positive only).
;   - NaN encoding is sign=1, exp=0, mant=0 (the "negative zero" slot).
;   - No Inf representation.

declare float @llvm.convert.from.arbitrary.fp.f32.i8(i8, metadata)
declare i8    @llvm.convert.to.arbitrary.fp.i8.f32(float, metadata, metadata, i1)

; ============================================================================
; Float8E4M3FNUZ — bias 8.
;   0x00 = +0
;   0x80 = NaN (the only NaN encoding)
;   0x40 = exp_field=8, mant=0 -> 2^(8-8) = 1.0
;   0xC0 = sign=1, exp_field=8, mant=0 -> -1.0
;   0x7F = exp_field=15, mant=7 -> 2^7 * (1 + 7/8) = 240
; ============================================================================

define float @from_e4m3fnuz_zero() {
; CHECK-LABEL: from_e4m3fnuz_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E4M3FNUZ")
  ret float %r
}

define float @from_e4m3fnuz_nan() {
; CHECK-LABEL: from_e4m3fnuz_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [NaN,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -128, metadata !"Float8E4M3FNUZ")
  ret float %r
}

define float @from_e4m3fnuz_one() {
; CHECK-LABEL: from_e4m3fnuz_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 64, metadata !"Float8E4M3FNUZ")
  ret float %r
}

define float @from_e4m3fnuz_neg_one() {
; CHECK-LABEL: from_e4m3fnuz_neg_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -64, metadata !"Float8E4M3FNUZ")
  ret float %r
}

define float @from_e4m3fnuz_max() {
; CHECK-LABEL: from_e4m3fnuz_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [2.4E+2,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 127, metadata !"Float8E4M3FNUZ")
  ret float %r
}

; +1.0 -> 0x40
define i8 @to_e4m3fnuz_one() {
; CHECK-LABEL: to_e4m3fnuz_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $64, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 1.0, metadata !"Float8E4M3FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; -1.0 -> 0xC0
define i8 @to_e4m3fnuz_neg_one() {
; CHECK-LABEL: to_e4m3fnuz_neg_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $-64, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float -1.0, metadata !"Float8E4M3FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; +0.0 -> 0x00 (FNUZ has only positive zero).
define i8 @to_e4m3fnuz_pos_zero() {
; CHECK-LABEL: to_e4m3fnuz_pos_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0.0, metadata !"Float8E4M3FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; -0.0 -> 0x00 (FNUZ collapses both zeros to +0; the sign=1, exp=0, mant=0
; encoding is reserved for NaN).
define i8 @to_e4m3fnuz_neg_zero() {
; CHECK-LABEL: to_e4m3fnuz_neg_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float -0.0, metadata !"Float8E4M3FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; A very small negative value that underflows to zero must produce +0, not
; the NaN encoding 0x80. This exercises the FNUZ negative-zero collision fix.
define i8 @to_e4m3fnuz_neg_underflow() {
; CHECK-LABEL: to_e4m3fnuz_neg_underflow:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0xB6A0000000000000, metadata !"Float8E4M3FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; NaN -> 0x80
define i8 @to_e4m3fnuz_nan() {
; CHECK-LABEL: to_e4m3fnuz_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $-128, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0x7FF8000000000000, metadata !"Float8E4M3FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; +Inf with saturate=true -> 0x7F (max finite).
define i8 @to_e4m3fnuz_inf_sat() {
; CHECK-LABEL: to_e4m3fnuz_inf_sat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $127, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0x7FF0000000000000, metadata !"Float8E4M3FNUZ", metadata !"round.tonearest", i1 true)
  ret i8 %r
}

; ============================================================================
; Float8E5M2FNUZ — bias 16.
;   0x00 = +0
;   0x80 = NaN
;   0x40 = exp_field=16, mant=0 -> 2^(16-16) = 1.0
; ============================================================================

define float @from_e5m2fnuz_zero() {
; CHECK-LABEL: from_e5m2fnuz_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E5M2FNUZ")
  ret float %r
}

define float @from_e5m2fnuz_nan() {
; CHECK-LABEL: from_e5m2fnuz_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [NaN,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -128, metadata !"Float8E5M2FNUZ")
  ret float %r
}

define float @from_e5m2fnuz_one() {
; CHECK-LABEL: from_e5m2fnuz_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 64, metadata !"Float8E5M2FNUZ")
  ret float %r
}

define i8 @to_e5m2fnuz_one() {
; CHECK-LABEL: to_e5m2fnuz_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $64, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 1.0, metadata !"Float8E5M2FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

define i8 @to_e5m2fnuz_neg_zero() {
; CHECK-LABEL: to_e5m2fnuz_neg_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float -0.0, metadata !"Float8E5M2FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

define i8 @to_e5m2fnuz_nan() {
; CHECK-LABEL: to_e5m2fnuz_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $-128, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0x7FF8000000000000, metadata !"Float8E5M2FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; ============================================================================
; Float8E4M3B11FNUZ — bias 11.
;   0x00 = +0
;   0x80 = NaN
;   0x58 = exp_field=11, mant=0 -> 2^(11-11) = 1.0
; ============================================================================

define float @from_e4m3b11fnuz_zero() {
; CHECK-LABEL: from_e4m3b11fnuz_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E4M3B11FNUZ")
  ret float %r
}

define float @from_e4m3b11fnuz_one() {
; CHECK-LABEL: from_e4m3b11fnuz_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 88, metadata !"Float8E4M3B11FNUZ")
  ret float %r
}

define i8 @to_e4m3b11fnuz_one() {
; CHECK-LABEL: to_e4m3b11fnuz_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $88, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 1.0, metadata !"Float8E4M3B11FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

define i8 @to_e4m3b11fnuz_nan() {
; CHECK-LABEL: to_e4m3b11fnuz_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $-128, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0x7FF8000000000000, metadata !"Float8E4M3B11FNUZ", metadata !"round.tonearest", i1 false)
  ret i8 %r
}
