; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; Test llvm.convert.{from,to}.arbitrary.fp expansion for Float8E8M0FNU.
;
; Float8E8M0FNU layout: 8-bit unsigned exponent only.
;   Encoding 0..254 represents 2^(encoding - 127).
;   Encoding 255 is NaN.
;   No sign bit, no mantissa, no Inf, no denormals, no zero.

declare float @llvm.convert.from.arbitrary.fp.f32.i8(i8, metadata)
declare half  @llvm.convert.from.arbitrary.fp.f16.i8(i8, metadata)
declare i8    @llvm.convert.to.arbitrary.fp.i8.f32(float, metadata, metadata, i1)
declare i8    @llvm.convert.to.arbitrary.fp.i8.f16(half,  metadata, metadata, i1)

; ============================================================================
; CONVERT_FROM_ARBITRARY_FP — constant folding sanity tests.
; ============================================================================

; Encoding 127 -> 2^0 = 1.0
define float @from_e8m0_one() {
; CHECK-LABEL: from_e8m0_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 127, metadata !"Float8E8M0FNU")
  ret float %r
}

; Encoding 128 -> 2^1 = 2.0
define float @from_e8m0_two() {
; CHECK-LABEL: from_e8m0_two:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [2.0E+0,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 128, metadata !"Float8E8M0FNU")
  ret float %r
}

; Encoding 126 -> 2^-1 = 0.5
define float @from_e8m0_half() {
; CHECK-LABEL: from_e8m0_half:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [5.0E-1,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 126, metadata !"Float8E8M0FNU")
  ret float %r
}

; Encoding 0 -> 2^-127 (denormal in f32: bits 0x00400000)
define float @from_e8m0_smallest() {
; CHECK-LABEL: from_e8m0_smallest:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [5.87747175E-39,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 0, metadata !"Float8E8M0FNU")
  ret float %r
}

; Encoding 254 -> 2^127 (largest finite in f32 normal range)
define float @from_e8m0_largest() {
; CHECK-LABEL: from_e8m0_largest:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [1.70141183E+38,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -2, metadata !"Float8E8M0FNU")
  ret float %r
}

; Encoding 255 -> NaN
define float @from_e8m0_nan() {
; CHECK-LABEL: from_e8m0_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [NaN,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 -1, metadata !"Float8E8M0FNU")
  ret float %r
}

; Variable input — exercises the full expansion path.
define float @from_e8m0_var(i8 %bits) {
; CHECK-LABEL: from_e8m0_var:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    movl $1, %edx
; CHECK-NEXT:    subl %eax, %edx
; CHECK-NEXT:    cmpl $31, %edx
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %edx, %ecx
; CHECK-NEXT:    movl $8388608, %edx # imm = 0x800000
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shll $23, %ecx
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    cmovlel %edx, %ecx
; CHECK-NEXT:    cmpl $255, %eax
; CHECK-NEXT:    movl $2139095040, %eax # imm = 0x7F800000
; CHECK-NEXT:    cmovll %ecx, %eax
; CHECK-NEXT:    movl $2143289344, %ecx # imm = 0x7FC00000
; CHECK-NEXT:    cmovnel %eax, %ecx
; CHECK-NEXT:    movd %ecx, %xmm0
; CHECK-NEXT:    retq
  %r = call float @llvm.convert.from.arbitrary.fp.f32.i8(i8 %bits, metadata !"Float8E8M0FNU")
  ret float %r
}

; ============================================================================
; CONVERT_TO_ARBITRARY_FP — constant folding sanity tests.
; ============================================================================

; +1.0 -> encoding 127.
define i8 @to_e8m0_one() {
; CHECK-LABEL: to_e8m0_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $127, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 1.0, metadata !"Float8E8M0FNU", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; +2.0 -> encoding 128.
define i8 @to_e8m0_two() {
; CHECK-LABEL: to_e8m0_two:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $-128, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 2.0, metadata !"Float8E8M0FNU", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; 0.5 -> encoding 126.
define i8 @to_e8m0_half() {
; CHECK-LABEL: to_e8m0_half:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $126, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0.5, metadata !"Float8E8M0FNU", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; +0.0 -> encoding 0 (clamp to minimum since E8M0 has no zero).
define i8 @to_e8m0_pos_zero() {
; CHECK-LABEL: to_e8m0_pos_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0.0, metadata !"Float8E8M0FNU", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; -1.0 -> encoding 0 (negative inputs clamp to minimum).
define i8 @to_e8m0_neg_one() {
; CHECK-LABEL: to_e8m0_neg_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float -1.0, metadata !"Float8E8M0FNU", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; NaN input -> encoding 255.
define i8 @to_e8m0_nan() {
; CHECK-LABEL: to_e8m0_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $-1, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0x7FF8000000000000, metadata !"Float8E8M0FNU", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; +Inf -> encoding 254 (clamp to maximum).
define i8 @to_e8m0_inf() {
; CHECK-LABEL: to_e8m0_inf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movb $-2, %al
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float 0x7FF0000000000000, metadata !"Float8E8M0FNU", metadata !"round.tonearest", i1 false)
  ret i8 %r
}
